MADNESS: madness::SliceLowRankTensor< T > Class Template Reference
madness::SliceLowRankTensor< T > Class Template Reference
implements a temporary(!) slice of a LowRankTensor
#include <lowranktensor.h>
Public Member Functions
SliceLowRankTensor ()
default ctor
SliceLowRankTensor (const GenTensor< T > &gt, const std::array< Slice, TENSOR_MAXDIM > &s)
ctor with a GenTensor; shallow
SliceLowRankTensor (const GenTensor< T > &gt, const std::vector< Slice > &s)
ctor with a GenTensor; shallow
void gaxpy (const std::array< Slice, TENSOR_MAXDIM > &lslice, const GenTensor< T > &rhs, const std::array< Slice, TENSOR_MAXDIM > &rslice, const double &beta)
*this = *this(s) + beta * rhs
SliceLowRankTensor< T > & operator+= (const GenTensor< T > &rhs)
inplace addition as in g(s)+=g1
SliceLowRankTensor< T > & operator+= (const SliceLowRankTensor< T > &rhs)
inplace addition as in g(s)+=g1(s)
SliceLowRankTensor< T > & operator-= (const GenTensor< T > &rhs)
inplace subtraction as in g(s)-=g1
SliceLowRankTensor< T > & operator-= (const SliceLowRankTensor< T > &rhs)
inplace addition as in g(s)-=g1(s)
SliceLowRankTensor< T > & operator= (const GenTensor< T > &rhs)
assignment as in g(s) = g1;
SliceLowRankTensor< T > & operator= (const SliceLowRankTensor< T > &rhs)
assignment as in g(s) = g1(s);
SliceLowRankTensor< T > & operator= (const T &number)
inplace zero-ing as in g(s)=0.0
Public Attributes
std::array< Slice, TENSOR_MAXDIM > thisslice
Friends
GenTensor< T > copy (const SliceLowRankTensor< T > &other)
Detailed Description
template<typename T>
class madness::SliceLowRankTensor< T >
implements a temporary(!) slice of a LowRankTensor
Constructor & Destructor Documentation
SliceLowRankTensor() [1/3]
template<typename T > madness::SliceLowRankTensor< T >::SliceLowRankTensor () inline
default ctor
SliceLowRankTensor() [2/3]
template<typename T > madness::SliceLowRankTensor< T >::SliceLowRankTensor (const GenTensor< T > & gt, const std::vector< Slice > & s) inline
ctor with a GenTensor; shallow
References madness::SliceLowRankTensor< T >::thisslice.
SliceLowRankTensor() [3/3]
template<typename T > madness::SliceLowRankTensor< T >::SliceLowRankTensor (const GenTensor< T > & gt, const std::array< Slice, TENSOR_MAXDIM > & s) inline
ctor with a GenTensor; shallow
Member Function Documentation
gaxpy()
template<typename T > void madness::SliceLowRankTensor< T >::gaxpy (const std::array< Slice, TENSOR_MAXDIM > & lslice, const GenTensor< T > & rhs, const std::array< Slice, TENSOR_MAXDIM > & rslice, const double & beta) inline
*this = *this(s) + beta * rhs
References beta, madness::GenTensor< T >::get_svdtensor(), madness::GenTensor< T >::get_tensor(), madness::GenTensor< T >::get_tensortrain(), madness::GenTensor< T >::has_no_data(), madness::is_same_tensor_type(), MADNESS_ASSERT, madness::GenTensor< T >::rank(), and madness::SliceLowRankTensor< T >::thisslice.
Referenced by madness::SliceLowRankTensor< T >::operator+=(), and madness::SliceLowRankTensor< T >::operator-=().
operator+=() [1/2]
template<typename T > SliceLowRankTensor<T>& madness::SliceLowRankTensor< T >::operator+= (const GenTensor< T > & rhs) inline
inplace addition as in g(s)+=g1
References madness::_(), madness::SliceLowRankTensor< T >::gaxpy(), and madness::SliceLowRankTensor< T >::thisslice.
operator+=() [2/2]
template<typename T > SliceLowRankTensor<T>& madness::SliceLowRankTensor< T >::operator+= (const SliceLowRankTensor< T > & rhs) inline
inplace addition as in g(s)+=g1(s)
References madness::SliceLowRankTensor< T >::gaxpy(), and madness::SliceLowRankTensor< T >::thisslice.
operator-=() [1/2]
template<typename T > SliceLowRankTensor<T>& madness::SliceLowRankTensor< T >::operator-= (const GenTensor< T > & rhs) inline
inplace subtraction as in g(s)-=g1
References madness::_(), madness::SliceLowRankTensor< T >::gaxpy(), and madness::SliceLowRankTensor< T >::thisslice.
operator-=() [2/2]
template<typename T > SliceLowRankTensor<T>& madness::SliceLowRankTensor< T >::operator-= (const SliceLowRankTensor< T > & rhs) inline
inplace addition as in g(s)-=g1(s)
References madness::SliceLowRankTensor< T >::gaxpy(), and madness::SliceLowRankTensor< T >::thisslice.
operator=() [1/3]
template<typename T > SliceLowRankTensor<T>& madness::SliceLowRankTensor< T >::operator= (const GenTensor< T > & rhs) inline
assignment as in g(s) = g1;
References MADNESS_ASSERT, and madness::print().
operator=() [2/3]
template<typename T > SliceLowRankTensor<T>& madness::SliceLowRankTensor< T >::operator= (const SliceLowRankTensor< T > & rhs) inline
assignment as in g(s) = g1(s);
References MADNESS_ASSERT, and madness::print().
operator=() [3/3]
template<typename T > SliceLowRankTensor<T>& madness::SliceLowRankTensor< T >::operator= (const T & number) inline
inplace zero-ing as in g(s)=0.0
References MADNESS_ASSERT, MADNESS_EXCEPTION, T(), and madness::SliceLowRankTensor< T >::thisslice.
Friends And Related Function Documentation
copy
template<typename T > GenTensor<T> copy (const SliceLowRankTensor< T > & other) friend
Member Data Documentation
thisslice
template<typename T > std::array<Slice,TENSOR_MAXDIM> madness::SliceLowRankTensor< T >::thisslice
Referenced by madness::SliceLowRankTensor< T >::gaxpy(), madness::GenTensor< T >::operator+(), madness::GenTensor< T >::operator+=(), madness::SliceLowRankTensor< T >::operator+=(), madness::GenTensor< T >::operator-=(), madness::SliceLowRankTensor< T >::operator-=(), madness::GenTensor< T >::operator=(), madness::SliceLowRankTensor< T >::operator=(), and madness::SliceLowRankTensor< T >::SliceLowRankTensor().
The documentation for this class was generated from the following file:
lowranktensor.h