MADNESS: density_vector Class Reference
density_vector Class Reference
#include <density.h>
Public Member Functions
density_vector (const density_vector &other)=default
density_vector (World &world, ResponseParameters r_params, GroundStateCalculation g_params)
ResponseParameters GetResponseParameters ()
Protected Attributes
X_space Chi
const GroundStateCalculation g_params
Molecule molecule
const size_t num_orbitals
const size_t num_states
Tensor< double > omega
VectorFunction3DT orbitals
X_space PQ
const std::string property
PropertyBase property_operator
const ResponseParameters r_params
VectorFunction3DT rho_omega
XCfunctional xcf
Friends
class TDDFT
Constructor & Destructor Documentation
density_vector() [1/2]
density_vector::density_vector (World & world, ResponseParameters r_params, GroundStateCalculation g_params)
References madness::ResponseParameters::excited_state(), madness::XCfunctional::initialize(), madness::ResponseParameters::num_states(), omega, madness::ResponseParameters::omega(), madness::ResponseParameters::print_level(), r_params, madness::ResponseParameters::spinrestricted(), madness::ResponseParameters::xc(), and xcf.
density_vector() [2/2]
density_vector::density_vector (const density_vector & other) default
Member Function Documentation
GetResponseParameters()
ResponseParameters density_vector::GetResponseParameters ()
References r_params.
Friends And Related Function Documentation
TDDFT
friend class TDDFT friend
Member Data Documentation
Chi
X_space density_vector::Chi protected
Referenced by TDDFT::TDDFT().
g_params
const GroundStateCalculation density_vector::g_params protected
molecule
Molecule density_vector::molecule protected
num_orbitals
const size_t density_vector::num_orbitals protected
num_states
const size_t density_vector::num_states protected
omega
Tensor<double> density_vector::omega protected
Referenced by density_vector().
orbitals
VectorFunction3DT density_vector::orbitals protected
PQ
X_space density_vector::PQ protected
Referenced by TDDFT::TDDFT().
property
const std::string density_vector::property protected
property_operator
PropertyBase density_vector::property_operator protected
r_params
const ResponseParameters density_vector::r_params protected
Referenced by density_vector(), and GetResponseParameters().
rho_omega
VectorFunction3DT density_vector::rho_omega protected
xcf
XCfunctional density_vector::xcf protected
Referenced by density_vector().
The documentation for this class was generated from the following files:
density.h
density.cc