MADNESS: TDDFT Class Reference
TDDFT Class Reference
#include <TDDFT.h>
Classes
class plotCoords
Public Member Functions
TDDFT (World &world, density_vector &rho)
response_space add_randomness (World &world, response_space &f, double magnitude)
void analysis (World &world, X_space &Chi)
void analyze_vectors (World &world, const vecfuncT &x, std::string response_state)
response_space apply_shift (World &world, double &shift, response_space &V, response_space &f)
response_space apply_shift (World &world, Tensor< double > &shifts, response_space &V, response_space &f)
void augment (World &world, X_space &Chi, X_space &old_Chi, X_space &Lambda_X, X_space &last_Lambda_X, Tensor< double > &S_x, Tensor< double > &A_x, Tensor< double > &old_S, Tensor< double > &old_A, size_t print_level)
Diagonolize in larger subspace x.
void augment_full (World &world, X_space &Chi, X_space &old_Chi, X_space &Lambda_X, X_space &last_Lambda_X, Tensor< double > &S_x, Tensor< double > &A_x, Tensor< double > &old_S, Tensor< double > &old_A, size_t print_level)
X_space bsh_update_excited (World &world, const Tensor< double > &omega, X_space &theta_X, QProjector< double, 3 > &projector)
Computes the BSH Update for an excited state calculation. Passes in omega and computes the necessary shifts in the potential, computes BSH operators and applys BSH operator.
X_space bsh_update_response (World &world, X_space &theta_X, std::vector< poperatorT > &bsh_x_ops, std::vector< poperatorT > &bsh_y_ops, QProjector< double, 3 > &projector, double &x_shifts)
Tensor< double > calculate_energy_update (World &world, response_space &gamma, response_space &f_residuals, response_space &new_f, size_t print_level, std::string xy)
double calculate_max_residual (World &world, response_space &f)
void check_k (World &world, double thresh, size_t k)
void compute_and_print_polarizability (World &world, X_space &Chi, X_space &PQ, std::string message)
X_space compute_F0X (World &world, X_space &Chi, XCOperator< double, 3 > xc, bool compute_Y)
X_space compute_gamma_full (World &world, X_space &Chi, const XCOperator< double, 3 > &xc)
X_space compute_gamma_static (World &world, X_space &Chi, XCOperator< double, 3 > xc)
X_space compute_gamma_tda (World &world, X_space &Chi, XCOperator< double, 3 > xc)
X_space Compute_Lambda_X (World &world, X_space &Chi, XCOperator< double, 3 > xc, std::string calc_type)
void compute_new_omegas_transform (World &world, X_space &old_Chi, X_space &Chi, X_space &old_Lambda_X, X_space &Lambda_X, Tensor< double > &omega, Tensor< double > &old_energy, Tensor< double > &S, Tensor< double > &old_S, Tensor< double > &A, Tensor< double > &old_A, Tensor< double > &energy_residuals, size_t iteration)
X_space compute_residual (World &world, X_space &old_Chi, X_space &temp, Tensor< double > &bsh_residualsX, Tensor< double > &bsh_residualsY, std::string calc_type)
X_space Compute_Theta_X (World &world, X_space &Chi, XCOperator< double, 3 > xc, std::string calc_type)
X_space compute_V0X (World &world, X_space &Chi, XCOperator< double, 3 > xc, bool compute_Y)
real_function_3d Coulomb (World &world)
std::vector< std::vector< std::shared_ptr< real_convolution_3d > > > create_bsh_operators (World &world, Tensor< double > &shift, Tensor< double > &ground, Tensor< double > &omega, double lo, double thresh)
std::vector< real_function_3d > create_fxc (World &world, std::vector< real_function_3d > &orbitals, response_space &f, response_space &g)
X_space create_nwchem_guess (World &world, size_t m)
X_space create_random_guess (World &world, size_t m, size_t n, vector_real_function_3d &grounds, Molecule &molecule)
std::vector< real_function_3d > create_random_guess (World &world, size_t m, std::vector< real_function_3d > &grounds, Molecule &molecule)
Tensor< double > create_shift (World &world, Tensor< double > &ground, Tensor< double > &omega, size_t print_level, std::string xy)
Tensor< double > create_shift_target (World &world, Tensor< double > &ground, Tensor< double > &omega, double target, size_t print_level, std::string xy)
X_space create_trial_functions (World &world, size_t k, std::vector< real_function_3d > &orbitals, size_t print_level)
X_space create_trial_functions2 (World &world, std::vector< real_function_3d > &orbitals, size_t print_level)
XCOperator< double, 3 > create_XCOperator (World &world, std::vector< real_function_3d > orbitals, std::string xc)
std::vector< std::shared_ptr< real_convolution_3d > > CreateBSHOperatorPropertyVector (World &world, double &shift, Tensor< double > &ground, double &omega, double lo, double thresh)
std::vector< std::vector< std::shared_ptr< real_convolution_3d > > > CreateBSHOperatorPropertyVector (World &world, Tensor< double > &shift, Tensor< double > &ground, Tensor< double > &omega, double lo, double thresh)
std::vector< real_function_3d > createDipoleFunctionMap (World &world)
Tensor< double > CreateGroundHamiltonian (World &world, std::vector< real_function_3d > f, size_t print_level)
std::vector< real_function_3d > CreateXCDerivative (World &world, const std::vector< real_function_3d > &orbitals, const response_space &f)
void deflateFull (World &world, X_space &Chi, X_space &old_Chi, X_space &Lambda_X, X_space &old_Lambda_X, Tensor< double > &S, Tensor< double > old_S, Tensor< double > old_A, Tensor< double > &omega, size_t &iteration, size_t &m)
void deflateGuesses (World &world, X_space &Chi, X_space &Lambda_X, Tensor< double > &S, Tensor< double > &omega, size_t &iteration, size_t &m)
Diagonalize AX=SX omega.
void deflateTDA (World &world, X_space &Chi, X_space &old_Chi, X_space &Lambda_X, X_space &old_Lambda_X, Tensor< double > &S, Tensor< double > old_S, Tensor< double > old_A, Tensor< double > &omega, size_t &iteration, size_t &m)
response_space diagonalize_CIS_guess (World &world, std::vector< real_function_3d > &virtuals, Tensor< double > &omega, std::vector< real_function_3d > &orbitals, Tensor< double > &energies, double lo, double thresh, size_t print_level)
Tensor< double > diagonalizeFockMatrix (World &world, X_space &Chi, X_space &Lambda_X, Tensor< double > &evals, Tensor< double > &A, Tensor< double > &S, const double thresh)
diagonalize the fock matrix, taking care of degenerate components
Tensor< double > diagonalizeFullResponseMatrix (World &world, X_space &Chi, X_space &Lambda_X, Tensor< double > &omega, Tensor< double > &S, Tensor< double > &A, const double thresh, size_t print_level)
double do_step_restriction (World &world, const vecfuncT &x, const vecfuncT &y, vecfuncT &x_new, vecfuncT &y_new, std::string spin) const
double do_step_restriction (World &world, const vecfuncT &x, vecfuncT &x_new, std::string spin) const
double do_step_restriction (World &world, const vecfuncT &x, vecfuncT &x_new, std::string spin, double maxrotn) const
response_space exchange (World &world, response_space &f)
Tensor< double > expectation (World &world, const response_space &a, const response_space &b)
Tensor< double > get_fock_transformation (World &world, Tensor< double > &overlap, Tensor< double > &fock, Tensor< double > &evals, const double thresh_degenerate)
compute the unitary transformation that diagonalizes the fock matrix
std::vector< real_function_3d > GetConjugateTransitionDensities (World &world, const std::vector< real_function_3d > &orbitals, const response_space &f)
std::vector< real_function_3d > GetConjugateWxcOnFDensities (World &world, const std::vector< real_function_3d > &orbitals, const response_space &f)
Tensor< double > GetFullResponseTransformation (World &world, Tensor< double > &S, Tensor< double > &A, Tensor< double > &evals, const double thresh)
std::vector< real_function_3d > GetTransitionDensities (World &world, const std::vector< real_function_3d > &orbitals, const response_space &f)
std::vector< real_function_3d > GetWxcOnFDensities (World &world, const std::vector< real_function_3d > &orbitals, const response_space &f)
response_space gram_schmidt (World &world, response_space &f)
void gram_schmidt (World &world, response_space &f, response_space &g)
void initial_load_bal (World &world)
void initialize_excited_json ()
void iterate_excited (World &world, X_space &Chi)
void iterate_freq2 (World &world)
void iterate_guess (World &world, X_space &guesses)
X_space kain_x_space_update (World &world, const X_space &temp, const X_space &res, NonLinearXsolver &kain_x_space, std::vector< X_vector > &Xvector, std::vector< X_vector > &Xresidual)
Computes the the X_space kain update.
void load (World &world, const std::string &name)
void load_balance (World &world, vecfuncT rho_omega, X_space Chi, const X_space &Chi_old)
std::vector< poperatorT > make_bsh_operators_response (World &world, double &shift, double &omega) const
vecfuncT make_density (World &world)
vecfuncT make_density (World &world, X_space &Chi, std::string calc_type)
functionT make_ground_density (World &world, const vecfuncT &v)
void make_nuclear_potential (World &world)
Tensor< double > matrix_exponential (const Tensor< double > &A)
void normalize (World &world, response_space &f, response_space &g)
void normalize (World &world, X_space &Chi)
void orbital_load_balance (World &world, vecfuncT &psi0, vecfuncT &psi0_copy, X_space &Chi, X_space &Chi_copy)
void output_json () const
void plot_excited_states (World &world, size_t iteration, response_space &x_response, response_space &y_response, ResponseParameters const &r_params, GroundStateCalculation const &g_params)
void PlotGroundandResponseOrbitals (World &world, size_t iteration, response_space &x_response, response_space &y_response, ResponseParameters const &r_params, GroundStateCalculation const &g_params)
Tensor< double > polarizability ()
void print_norms (World &world, response_space function)
void print_residual_norms (World &world, X_space &old_Chi, bool compute_y, size_t iteration)
void PrintPolarizabilityAnalysis (World &world, const Tensor< double > polar_tensor)
void PrintResponseVectorNorms (World &world, response_space f, std::string fname)
void PrintRFExpectation (World &world, response_space f, response_space g, std::string fname, std::string gname)
vecfuncT project_ao_basis (World &world, const AtomicBasisSet &aobasis)
vecfuncT project_ao_basis_only (World &world, const AtomicBasisSet &aobasis, const Molecule &molecule)
response_space PropertyRHS (World &world, PropertyBase &p) const
void save (World &world, const std::string &name)
void select_active_subspace (World &world)
response_space select_functions (World &world, response_space &f, Tensor< double > &energies, size_t k, size_t print_level)
template<std::size_t NDIM>
void set_protocol (World &world, double thresh)
plotCoords SetPlotCoord (size_t i, double Lp)
std::map< std::vector< int >, real_function_3d > simple_spherical_harmonics (World &world, int n)
std::map< std::vector< int >, real_function_3d > solid_harmonics (World &world, int n)
void solve_excited_states (World &world)
void solve_response_states (World &world)
void sort (World &world, Tensor< double > &vals, response_space &f)
void sort (World &world, Tensor< double > &vals, X_space &f)
Tensor< int > sort_eigenvalues (World &world, Tensor< double > &vals, Tensor< double > &vecs)
response_space transform (World &world, response_space &f, Tensor< double > &U)
std::vector< real_function_3d > transition_density (World &world, std::vector< real_function_3d > &orbitals, response_space &x, response_space &y)
std::vector< real_function_3d > transition_densityTDA (World &world, std::vector< real_function_3d > const &orbitals, response_space &x)
void unaugment (World &world, X_space &Chi, X_space &old_Chi, X_space &Lambda_X, X_space &last_Lambda_X, Tensor< double > &omega, Tensor< double > &S_x, Tensor< double > &A_x, Tensor< double > &old_S, Tensor< double > &old_A, size_t num_states, size_t iter, size_t print_level)
void unaugment_full (World &world, X_space &Chi, X_space &old_Chi, X_space &Lambda_X, X_space &last_Lambda_X, Tensor< double > &omega, Tensor< double > &S_x, Tensor< double > &A_x, Tensor< double > &old_S, Tensor< double > &old_A, size_t num_states, size_t iter, size_t print_level)
void update_x_space_excited (World &world, X_space &old_Chi, X_space &Chi, X_space &old_Lambda_X, X_space &residuals, XCOperator< double, 3 > &xc, QProjector< double, 3 > &projector, Tensor< double > &omega, NonLinearXsolver &kain_x_space, std::vector< X_vector > &Xvector, std::vector< X_vector > &Xresidual, Tensor< double > &energy_residuals, Tensor< double > &old_energy, Tensor< double > &bsh_residualsX, Tensor< double > &bsh_residualsY, Tensor< double > &S, Tensor< double > &old_S, Tensor< double > &A, Tensor< double > &old_A, size_t iteration, Tensor< double > &maxrotn)
void update_x_space_response (World &world, X_space &Chi, X_space &residual, XCOperator< double, 3 > &xc, std::vector< poperatorT > &bsh_x_ops, std::vector< poperatorT > &bsh_y_ops, QProjector< double, 3 > &projector, double &x_shifts, double &omega_n, NonLinearXsolver &kain_x_space, std::vector< X_vector > Xvector, std::vector< X_vector > Xresidual, Tensor< double > &bsh_residualsX, Tensor< double > &bsh_residualsY, size_t iteration, Tensor< double > &maxrotn)
void vector_stats (const std::vector< double > &v, double &rms, double &maxabsval) const
void vector_stats_new (const Tensor< double > v, double &rms, double &maxabsval) const
void x_space_step_restriction (World &world, X_space &old_Chi, X_space &temp, bool restrict_y, Tensor< double > &maxrotn)
Static Public Member Functions
static void excited_to_json (nlohmann::json &json, size_t iter, const Tensor< double > &tensor, const Tensor< double > &tensor1, const Tensor< double > &tensor2, const Tensor< double > &tensor3)
static void frequency_to_json (nlohmann::json &json, size_t iter, const Tensor< double > &tensor, const Tensor< double > &tensor1, const Tensor< double > &tensor2, const Tensor< double > &tensor3)
static void normalize (World &world, response_space &f)
Public Attributes
Tensor< double > act_ground_energies
unsigned int act_num_orbitals
std::vector< real_function_3d > act_orbitals
std::vector< int > active
X_space Chi
poperatorT coulop
Tensor< double > e_residuals
GroundStateCalculation g_params
std::vector< std::shared_ptr< real_derivative_3d > > gradop
Tensor< double > ground_energies
std::vector< real_function_3d > ground_orbitals
Tensor< double > ham_no_diag
Tensor< double > hamiltonian
nlohmann::json j_molresponse
functionT mask
Molecule molecule
Tensor< double > omega
PropertyBase p
std::shared_ptr< PotentialManager > potential_manager
X_space PQ
ResponseParameters r_params
density_vector rho
functionT rho0
vecfuncT rho_omega
response_space stored_potential
real_function_3d stored_v_coul
real_function_3d stored_v_nuc
double vtol
XCfunctional xcf
Constructor & Destructor Documentation
TDDFT()
TDDFT::TDDFT (World & world, density_vector & rho)
References madness::LoadBalanceDeux< NDIM >::add_tree(), madness::WorldGopInterface::broadcast_serializable(), density_vector::Chi, Chi, molresponse::end_timer(), f, g_params, GroundStateCalculation::get_energies(), madness::World::gop, ground_energies, ground_orbitals, j_molresponse, madness::ResponseParameters::L(), madness::LoadBalanceDeux< NDIM >::load_balance(), mask, mask3(), molecule, madness::ResponseParameters::num_orbitals(), GroundStateCalculation::orbitals(), density_vector::PQ, PQ, print(), madness::ResponseParameters::print_level(), r_params, madness::World::rank(), rho, madness::World::size(), molresponse::start_timer(), and madness::ResponseParameters::to_json().
Member Function Documentation
add_randomness()
response_space TDDFT::add_randomness (World & world, response_space & f, double magnitude)
References f, madness::Tensor< T >::fillrandom(), mask, madness::Tensor< T >::scale(), and madness::response_space::size().
analysis()
void TDDFT::analysis (World & world, X_space & Chi)
References madness::_(), Chi, madness::copy(), ground_orbitals, madness::inner(), m, madness::Tensor< T >::max(), madness::response_space::norm2(), omega, print(), r_params, madness::World::rank(), madness::response_space::size(), madness::ResponseParameters::tda(), madness::X_space::X, and madness::X_space::Y.
Referenced by iterate_excited().
analyze_vectors()
void TDDFT::analyze_vectors (World & world, const vecfuncT & x, std::string response_state)
References madness::_(), axis, C, molresponse::end_timer(), madness::inner(), madness::matrix_inner(), molecule, madness::mul_sparse(), print(), madness::AtomicBasisSet::print_anal(), madness::ResponseParameters::print_level(), project_ao_basis(), r_params, madness::World::rank(), rsquared(), molresponse::start_timer(), and vtol.
Referenced by iterate_excited().
apply_shift() [1/2]
response_space TDDFT::apply_shift (World & world, double & shift, response_space & V, response_space & f)
References molresponse::end_timer(), f, k, m, p, madness::ResponseParameters::print_level(), r_params, shift, molresponse::start_timer(), madness::response_space::truncate_rf(), and V().
apply_shift() [2/2]
response_space TDDFT::apply_shift (World & world, Tensor< double > & shifts, response_space & V, response_space & f)
References molresponse::end_timer(), f, k, m, p, madness::ResponseParameters::print_level(), r_params, molresponse::start_timer(), madness::response_space::truncate_rf(), and V().
Referenced by bsh_update_excited(), and iterate_guess().
augment()
void TDDFT::augment (World & world, X_space & Chi, X_space & old_Chi, X_space & Lambda_X, X_space & last_Lambda_X, Tensor< double > & S, Tensor< double > & A, Tensor< double > & old_S, Tensor< double > & old_A, size_t print_level)
Diagonolize in larger subspace x.
Parameters
world
S <x|x>
A <x|Ax>
Current Ax
Last Axold
x_response
old_S
old_A
old_x_response
print_level
Need to create off diagonal blocks of A A= [xAx xAx_old ] [xoldAx xoldAxold]
Creating S S= [<x|x> <x|xold> ] [<xold|x> <xold|xold>]
References Chi, madness::copy(), molresponse::end_timer(), expectation(), m, print(), madness::response_space::push_back(), madness::World::rank(), madness::response_space::size(), molresponse::start_timer(), madness::transpose(), and madness::X_space::X.
Referenced by deflateTDA().
augment_full()
void TDDFT::augment_full (World & world, X_space & Chi, X_space & old_Chi, X_space & Lambda_X, X_space & last_Lambda_X, Tensor< double > & S_x, Tensor< double > & A_x, Tensor< double > & old_S, Tensor< double > & old_A, size_t print_level)
References Chi, madness::copy(), molresponse::end_timer(), madness::inner(), m, madness::X_space::num_states(), print(), madness::X_space::push_back(), madness::World::rank(), molresponse::start_timer(), madness::transpose(), madness::X_space::X, and madness::X_space::Y.
Referenced by deflateFull().
bsh_update_excited()
X_space TDDFT::bsh_update_excited (World & world, const Tensor< double > & omega, X_space & theta_X, QProjector< double, 3 > & projector)
Computes the BSH Update for an excited state calculation. Passes in omega and computes the necessary shifts in the potential, computes BSH operators and applys BSH operator.
Parameters
world
theta_X
projector
converged
Returns
X_space
References madness::apply(), apply_shift(), Chi, create_bsh_operators(), create_shift(), ground_energies, madness::ResponseParameters::lo(), m, mask, madness::X_space::num_orbitals(), madness::X_space::num_states(), omega, print(), madness::ResponseParameters::print_level(), r_params, madness::ResponseParameters::tda(), madness::X_space::truncate(), madness::response_space::truncate_rf(), madness::X_space::X, and madness::X_space::Y.
Referenced by update_x_space_excited().
bsh_update_response()
X_space TDDFT::bsh_update_response (World & world, X_space & theta_X, std::vector< poperatorT > & bsh_x_ops, std::vector< poperatorT > & bsh_y_ops, QProjector< double, 3 > & projector, double & x_shifts)
References madness::apply(), Chi, madness::response_space::copy(), molresponse::end_timer(), m, madness::ResponseParameters::omega(), PQ, r_params, madness::response_space::size(), madness::response_space::size_orbitals(), molresponse::start_timer(), madness::X_space::truncate(), madness::response_space::truncate_rf(), madness::X_space::X, and madness::X_space::Y.
Referenced by update_x_space_response().
calculate_energy_update()
Tensor< double > TDDFT::calculate_energy_update (World & world, response_space & gamma, response_space & f_residuals, response_space & new_f, size_t print_level, std::string xy)
References madness::abs(), madness::inner(), k, m, print(), madness::World::rank(), and madness::response_space::size().
calculate_max_residual()
double TDDFT::calculate_max_residual (World & world, response_space & f)
References f, max, madness::norm2(), and pow().
check_k()
void TDDFT::check_k (World & world, double thresh, size_t k)
References Chi, CreateGroundHamiltonian(), madness::WorldGopInterface::fence(), g_params, madness::World::gop, ground_orbitals, hamiltonian, madness::Tensor< T >::has_data(), k, madness::Function< T, NDIM >::k(), mask, PQ, madness::ResponseParameters::print_level(), madness::project(), r_params, GroundStateCalculation::read(), madness::reconstruct(), madness::response_space::size(), madness::ResponseParameters::store_potential(), stored_potential, stored_v_coul, stored_v_nuc, thresh, madness::truncate(), madness::response_space::truncate_rf(), madness::X_space::X, and madness::X_space::Y.
Referenced by solve_excited_states(), and solve_response_states().
compute_and_print_polarizability()
void TDDFT::compute_and_print_polarizability (World & world, X_space & Chi, X_space & PQ, std::string message)
References Chi, madness::inner(), PQ, print(), and madness::World::rank().
Referenced by iterate_freq2(), and update_x_space_response().
compute_F0X()
X_space TDDFT::compute_F0X (World & world, X_space & Chi, XCOperator< double, 3 > xc, bool compute_Y)
References Chi, compute_V0X(), madness::X_space::copy(), molresponse::end_timer(), madness::inner(), m, madness::X_space::num_orbitals(), madness::X_space::num_states(), print(), madness::ResponseParameters::print_level(), r_params, molresponse::start_timer(), T(), madness::X_space::X, xc, and madness::X_space::Y.
Referenced by Compute_Lambda_X().
compute_gamma_full()
X_space TDDFT::compute_gamma_full (World & world, X_space & Chi, const XCOperator< double, 3 > & xc)
References madness::apply(), b, Chi, madness::X_space::clear(), madness::response_space::copy(), coulop, madness::dot(), molresponse::end_timer(), madness::WorldGopInterface::fence(), madness::World::gop, ground_orbitals, madness::XCfunctional::hf_exchange_coefficient(), madness::inner(), K(), m, madness::mul(), madness::X_space::num_orbitals(), madness::X_space::num_states(), orbital_load_balance(), print(), madness::ResponseParameters::print_level(), r_params, rho_omega, madness::World::size(), molresponse::start_timer(), madness::truncate(), madness::X_space::truncate(), madness::Function< T, NDIM >::truncate(), madness::X_space::X, xc, xcf, and madness::X_space::Y.
Referenced by Compute_Lambda_X(), and Compute_Theta_X().
compute_gamma_static()
X_space TDDFT::compute_gamma_static (World & world, X_space & Chi, XCOperator< double, 3 > xc)
References madness::apply(), b, Chi, madness::X_space::clear(), coulop, molresponse::end_timer(), madness::WorldGopInterface::fence(), madness::World::gop, ground_orbitals, madness::XCfunctional::hf_exchange_coefficient(), K(), m, madness::mul(), madness::ResponseParameters::num_orbitals(), madness::ResponseParameters::num_states(), orbital_load_balance(), r_params, rho_omega, madness::World::size(), molresponse::start_timer(), madness::X_space::truncate(), madness::Function< T, NDIM >::truncate(), madness::X_space::X, xc, xcf, and madness::X_space::Y.
Referenced by Compute_Lambda_X(), and Compute_Theta_X().
compute_gamma_tda()
X_space TDDFT::compute_gamma_tda (World & world, X_space & Chi, XCOperator< double, 3 > xc)
References madness::apply(), b, Chi, madness::X_space::clear(), madness::response_space::clear(), coulop, molresponse::end_timer(), madness::WorldGopInterface::fence(), madness::World::gop, ground_orbitals, madness::XCfunctional::hf_exchange_coefficient(), K(), m, madness::mul(), madness::response_space::norm2(), madness::X_space::num_orbitals(), madness::X_space::num_states(), orbital_load_balance(), print(), madness::ResponseParameters::print_level(), PrintResponseVectorNorms(), PrintRFExpectation(), r_params, rho_omega, madness::World::size(), molresponse::start_timer(), madness::truncate(), madness::Function< T, NDIM >::truncate(), madness::response_space::truncate_rf(), madness::X_space::X, xc, and xcf.
Referenced by Compute_Lambda_X(), and Compute_Theta_X().
Compute_Lambda_X()
X_space TDDFT::Compute_Lambda_X (World & world, X_space & Chi, XCOperator< double, 3 > xc, std::string calc_type)
References Chi, compute_F0X(), compute_gamma_full(), compute_gamma_static(), compute_gamma_tda(), madness::X_space::copy(), hamiltonian, madness::inner(), print(), madness::ResponseParameters::print_level(), r_params, madness::X_space::truncate(), madness::X_space::X, xc, and madness::X_space::Y.
Referenced by iterate_guess(), and update_x_space_excited().
compute_new_omegas_transform()
void TDDFT::compute_new_omegas_transform (World & world, X_space & old_Chi, X_space & Chi, X_space & old_Lambda_X, X_space & Lambda_X, Tensor< double > & omega, Tensor< double > & old_energy, Tensor< double > & S, Tensor< double > & old_S, Tensor< double > & A, Tensor< double > & old_A, Tensor< double > & energy_residuals, size_t iteration)
References madness::abs(), Chi, deflateFull(), deflateTDA(), m, omega, print(), madness::ResponseParameters::print_level(), r_params, madness::World::rank(), madness::response_space::size(), madness::ResponseParameters::tda(), and madness::X_space::X.
Referenced by update_x_space_excited().
compute_residual()
X_space TDDFT::compute_residual (World & world, X_space & old_Chi, X_space & temp, Tensor< double > & bsh_residualsX, Tensor< double > & bsh_residualsY, std::string calc_type)
References madness::response_space::copy(), molresponse::end_timer(), madness::Tensor< T >::fill(), m, madness::response_space::norm2(), madness::norm2s(), print(), madness::ResponseParameters::print_level(), r_params, madness::World::rank(), madness::response_space::size(), madness::response_space::size_orbitals(), molresponse::start_timer(), vector_stats(), madness::X_space::X, and madness::X_space::Y.
Referenced by update_x_space_excited(), and update_x_space_response().
Compute_Theta_X()
X_space TDDFT::Compute_Theta_X (World & world, X_space & Chi, XCOperator< double, 3 > xc, std::string calc_type)
References Chi, compute_gamma_full(), compute_gamma_static(), compute_gamma_tda(), compute_V0X(), madness::X_space::copy(), ham_no_diag, madness::inner(), madness::ResponseParameters::localize(), madness::X_space::num_orbitals(), madness::X_space::num_states(), print(), madness::ResponseParameters::print_level(), r_params, madness::X_space::truncate(), madness::X_space::X, xc, and madness::X_space::Y.
Referenced by iterate_guess(), update_x_space_excited(), and update_x_space_response().
compute_V0X()
X_space TDDFT::compute_V0X (World & world, X_space & Chi, XCOperator< double, 3 > xc, bool compute_Y)
References madness::apply(), b, Chi, coulop, molresponse::end_timer(), ground_orbitals, madness::XCfunctional::hf_exchange_coefficient(), madness::inner(), K(), m, madness::X_space::num_orbitals(), madness::X_space::num_states(), potential_manager, print(), madness::ResponseParameters::print_level(), r_params, rho0, madness::Function< T, NDIM >::scale(), molresponse::start_timer(), madness::ResponseParameters::store_potential(), stored_v_coul, stored_v_nuc, madness::truncate(), madness::X_space::truncate(), madness::Function< T, NDIM >::truncate(), madness::X_space::X, xc, xcf, and madness::X_space::Y.
Referenced by compute_F0X(), and Compute_Theta_X().
Coulomb()
real_function_3d TDDFT::Coulomb (World & world)
References madness::apply(), madness::compress(), madness::CoulombOperator(), madness::WorldGopInterface::fence(), madness::World::gop, ground_orbitals, madness::ResponseParameters::lo(), op(), r_params, rho, and square().
Referenced by CreateGroundHamiltonian().
create_bsh_operators()
std::vector< std::vector< std::shared_ptr< real_convolution_3d > > > TDDFT::create_bsh_operators (World & world, Tensor< double > & shift, Tensor< double > & ground, Tensor< double > & omega, double lo, double thresh)
References madness::BSHOperatorPtr3D(), molresponse::end_timer(), k, lo, m, mu, omega, p, print(), madness::ResponseParameters::print_level(), r_params, shift, molresponse::start_timer(), and thresh.
Referenced by bsh_update_excited(), and iterate_guess().
create_fxc()
std::vector< real_function_3d > TDDFT::create_fxc (World & world, std::vector< real_function_3d > & orbitals, response_space & f, response_space & g)
References create_XCOperator(), f, g(), ground_orbitals, r_params, transition_density(), xc, and madness::ResponseParameters::xc().
create_nwchem_guess()
X_space TDDFT::create_nwchem_guess (World & world, size_t m)
References slymer::Properties::Basis, slymer::ES_Interface::basis_set, create_random_guess(), slymer::Properties::Energies, slymer::ES_Interface::err, f, g_params, ground_orbitals, m, max, GroundStateCalculation::molecule(), slymer::Properties::MOs, slymer::ES_Interface::MOs, normalize(), madness::normalize(), madness::X_space::num_states(), madness::ResponseParameters::nwchem_dir(), slymer::Properties::Occupancies, slymer::ES_Interface::occupancies, GroundStateCalculation::orbitals(), print(), r_params, madness::World::rank(), slymer::NWChem_Interface::read(), madness::transform(), and madness::X_space::X.
Referenced by solve_excited_states().
create_random_guess() [1/2]
X_space TDDFT::create_random_guess (World & world, size_t m, size_t n, vector_real_function_3d & grounds, Molecule & molecule)
Referenced by create_nwchem_guess(), and solve_excited_states().
create_random_guess() [2/2]
std::vector< real_function_3d > TDDFT::create_random_guess (World & world, size_t m, std::vector< real_function_3d > & grounds, Molecule & molecule)
References f, madness::Tensor< T >::fillrandom(), madness::Molecule::get_atoms(), lambda, m, mask, molecule, madness::detail::norm(), print(), madness::World::rank(), madness::Tensor< T >::scale(), and madness::Function< T, NDIM >::size().
create_shift()
Tensor< double > TDDFT::create_shift (World & world, Tensor< double > & ground, Tensor< double > & omega, size_t print_level, std::string xy)
References molresponse::end_timer(), k, m, omega, p, print(), madness::World::rank(), and molresponse::start_timer().
Referenced by bsh_update_excited(), and iterate_guess().
create_shift_target()
Tensor< double > TDDFT::create_shift_target (World & world, Tensor< double > & ground, Tensor< double > & omega, double target, size_t print_level, std::string xy)
References molresponse::end_timer(), k, m, omega, p, print(), madness::World::rank(), molresponse::start_timer(), and target().
create_trial_functions()
X_space TDDFT::create_trial_functions (World & world, size_t k, std::vector< real_function_3d > & orbitals, size_t print_level)
References madness::response_space::clear(), madness::response_space::copy(), k, max, print(), print_norms(), madness::response_space::push_back(), madness::World::rank(), solid_harmonics(), madness::truncate(), and madness::X_space::X.
Referenced by solve_excited_states().
create_trial_functions2()
X_space TDDFT::create_trial_functions2 (World & world, std::vector< real_function_3d > & orbitals, size_t print_level)
References madness::copy(), createDipoleFunctionMap(), d(), madness::norm2(), print(), print_norms(), madness::World::rank(), madness::truncate(), and madness::X_space::X.
Referenced by solve_excited_states().
create_XCOperator()
XCOperator< double, 3 > TDDFT::create_XCOperator (World & world, std::vector< real_function_3d > orbitals, std::string xc)
References madness::compress(), madness::WorldGopInterface::fence(), madness::World::gop, ground_orbitals, rho, square(), and xc.
Referenced by create_fxc(), CreateGroundHamiltonian(), CreateXCDerivative(), GetConjugateWxcOnFDensities(), GetWxcOnFDensities(), iterate_excited(), iterate_freq2(), and iterate_guess().
CreateBSHOperatorPropertyVector() [1/2]
std::vector< std::shared_ptr< real_convolution_3d > > TDDFT::CreateBSHOperatorPropertyVector (World & world, double & shift, Tensor< double > & ground, double & omega, double lo, double thresh)
References madness::BSHOperatorPtr3D(), molresponse::end_timer(), lo, mu, omega, p, madness::ResponseParameters::print_level(), r_params, shift, and molresponse::start_timer().
CreateBSHOperatorPropertyVector() [2/2]
std::vector< std::vector< std::shared_ptr< real_convolution_3d > > > TDDFT::CreateBSHOperatorPropertyVector (World & world, Tensor< double > & shift, Tensor< double > & ground, Tensor< double > & omega, double lo, double thresh)
References madness::BSHOperatorPtr3D(), molresponse::end_timer(), k, lo, madness::ResponseParameters::num_states(), omega, p, madness::ResponseParameters::print_level(), r_params, shift, molresponse::start_timer(), and thresh.
createDipoleFunctionMap()
std::vector< real_function_3d > TDDFT::createDipoleFunctionMap (World & world)
Referenced by create_trial_functions2().
CreateGroundHamiltonian()
Tensor< double > TDDFT::CreateGroundHamiltonian (World & world, std::vector< real_function_3d > f, size_t print_level)
References madness::apply(), madness::response_space::clear(), madness::Function< T, NDIM >::clear(), madness::compress(), madness::copy(), Coulomb(), madness::CoulombOperator(), create_XCOperator(), molresponse::end_timer(), f, madness::WorldGopInterface::fence(), g_params, madness::gaxpy(), madness::World::gop, ham_no_diag, hamiltonian, madness::ResponseParameters::lo(), m, madness::PotentialManager::make_nuclear_potential(), madness::XCOperator< T, NDIM >::make_xc_potential(), madness::matrix_inner(), GroundStateCalculation::molecule(), madness::mul_sparse(), op(), print(), madness::response_space::push_back(), r_params, madness::World::rank(), madness::reconstruct(), molresponse::start_timer(), madness::ResponseParameters::store_potential(), stored_potential, stored_v_coul, stored_v_nuc, T(), madness::truncate(), madness::Function< T, NDIM >::truncate(), V(), madness::PotentialManager::vnuclear(), madness::ResponseParameters::xc(), and madness::XCOperator< T, NDIM >::xc.
Referenced by check_k(), and diagonalize_CIS_guess().
CreateXCDerivative()
std::vector< real_function_3d > TDDFT::CreateXCDerivative (World & world, const std::vector< real_function_3d > & orbitals, const response_space & f)
References create_XCOperator(), f, ground_orbitals, m, r_params, xc, and madness::ResponseParameters::xc().
deflateFull()
void TDDFT::deflateFull (World & world, X_space & Chi, X_space & old_Chi, X_space & Lambda_X, X_space & old_Lambda_X, Tensor< double > & S, Tensor< double > old_S, Tensor< double > old_A, Tensor< double > & omega, size_t & iteration, size_t & m)
References augment_full(), Chi, madness::Tensor< T >::clear(), madness::X_space::copy(), diagonalizeFullResponseMatrix(), madness::inner(), madness::ResponseParameters::larger_subspace(), madness::ResponseParameters::num_states(), omega, print(), madness::ResponseParameters::print_level(), r_params, madness::World::rank(), madness::X_space::truncate(), unaugment_full(), madness::X_space::X, and madness::X_space::Y.
Referenced by compute_new_omegas_transform().
deflateGuesses()
void TDDFT::deflateGuesses (World & world, X_space & Chi, X_space & Lambda_X, Tensor< double > & S, Tensor< double > & omega, size_t & iteration, size_t & m)
Diagonalize AX=SX omega.
Parameters
world
S
old_S
old_A
x_response
old_x_response
ElectronResponses
OldElectronResponses
omega
iteration
m
References Chi, madness::Tensor< T >::clear(), diagonalizeFockMatrix(), omega, print(), madness::ResponseParameters::print_level(), r_params, madness::World::rank(), and madness::X_space::X.
Referenced by iterate_guess().
deflateTDA()
void TDDFT::deflateTDA (World & world, X_space & Chi, X_space & old_Chi, X_space & Lambda_X, X_space & old_Lambda_X, Tensor< double > & S, Tensor< double > old_S, Tensor< double > old_A, Tensor< double > & omega, size_t & iteration, size_t & m)
References augment(), Chi, madness::Tensor< T >::clear(), diagonalizeFockMatrix(), madness::ResponseParameters::larger_subspace(), madness::ResponseParameters::num_states(), omega, print(), madness::ResponseParameters::print_level(), r_params, madness::World::rank(), unaugment(), and madness::X_space::X.
Referenced by compute_new_omegas_transform().
diagonalize_CIS_guess()
response_space TDDFT::diagonalize_CIS_guess (World & world, std::vector< real_function_3d > & virtuals, Tensor< double > & omega, std::vector< real_function_3d > & orbitals, Tensor< double > & energies, double lo, double thresh, size_t print_level)
References a, madness::apply(), b, madness::compress(), madness::CoulombOperator(), CreateGroundHamiltonian(), molresponse::end_timer(), f, get_fock_transformation(), I, madness::inner(), lo, m, MADNESS_EXCEPTION, madness::matrix_inner(), omega, op(), print(), madness::ResponseParameters::print_level(), r_params, madness::World::rank(), molresponse::start_timer(), madness::syev(), thresh, madness::transform(), and madness::truncate().
diagonalizeFockMatrix()
Tensor< double > TDDFT::diagonalizeFockMatrix (World & world, X_space & Chi, X_space & Lambda_X, Tensor< double > & evals, Tensor< double > & A, Tensor< double > & S, const double thresh)
diagonalize the fock matrix, taking care of degenerate components
Vpsi is passed in to make sure orbitals and Vpsi are in phase
Parameters
[in] world the world
[in] fock
[in,out] psi the orbitals
[in,out] Vpsi the orbital times the potential
[in,out] gamma the orbital times the perturbed potential
[out] evals the orbital energies
[in] overlap the overlap matrix
[in] thresh threshold for rotation and truncation
References Chi, molresponse::end_timer(), get_fock_transformation(), normalize(), print(), madness::ResponseParameters::print_level(), r_params, madness::World::rank(), sort_eigenvalues(), molresponse::start_timer(), thresh, transform(), and madness::X_space::X.
Referenced by deflateGuesses(), and deflateTDA().
diagonalizeFullResponseMatrix()
Tensor< double > TDDFT::diagonalizeFullResponseMatrix (World & world, X_space & Chi, X_space & Lambda_X, Tensor< double > & omega, Tensor< double > & S, Tensor< double > & A, const double thresh, size_t print_level)
References Chi, molresponse::end_timer(), GetFullResponseTransformation(), normalize(), omega, print(), madness::ResponseParameters::print_level(), r_params, madness::World::rank(), molresponse::start_timer(), thresh, transform(), madness::X_space::X, and madness::X_space::Y.
Referenced by deflateFull().
do_step_restriction() [1/3]
double TDDFT::do_step_restriction (World & world, const vecfuncT & x, const vecfuncT & y, vecfuncT & x_new, vecfuncT & y_new, std::string spin) const
References madness::WorldGopInterface::fence(), madness::World::gop, madness::ResponseParameters::maxrotn(), madness::norm2s_T(), print(), madness::ResponseParameters::print_level(), r_params, madness::World::rank(), madness::sub(), and vector_stats_new().
do_step_restriction() [2/3]
double TDDFT::do_step_restriction (World & world, const vecfuncT & x, vecfuncT & x_new, std::string spin) const
References madness::WorldGopInterface::fence(), madness::World::gop, madness::ResponseParameters::maxrotn(), madness::norm2s(), print(), madness::ResponseParameters::print_level(), r_params, madness::World::rank(), madness::sub(), and vector_stats().
Referenced by x_space_step_restriction().
do_step_restriction() [3/3]
double TDDFT::do_step_restriction (World & world, const vecfuncT & x, vecfuncT & x_new, std::string spin, double maxrotn) const
References madness::WorldGopInterface::fence(), madness::Tensor< T >::gaxpy(), madness::World::gop, madness::norm2s_T(), print(), madness::ResponseParameters::print_level(), r_params, madness::World::rank(), madness::sub(), and vector_stats_new().
exchange()
response_space TDDFT::exchange (World & world, response_space & f)
References madness::apply(), coulop, f, madness::gaxpy(), ground_orbitals, k, m, madness::mul_sparse(), and madness::truncate().
excited_to_json()
void TDDFT::excited_to_json (nlohmann::json & json, size_t iter, const Tensor< double > & tensor, const Tensor< double > & tensor1, const Tensor< double > & tensor2, const Tensor< double > & tensor3) static
References omega.
Referenced by iterate_excited().
expectation()
Tensor< double > TDDFT::expectation (World & world, const response_space & a, const response_space & b)
[x1 x2 x3]T[x1 x2 x3]
References MADNESS_ASSERT, madness::matrix_inner(), and p.
Referenced by augment().
frequency_to_json()
void TDDFT::frequency_to_json (nlohmann::json & json, size_t iter, const Tensor< double > & tensor, const Tensor< double > & tensor1, const Tensor< double > & tensor2, const Tensor< double > & tensor3) static
References omega.
Referenced by iterate_freq2().
get_fock_transformation()
Tensor< double > TDDFT::get_fock_transformation (World & world, Tensor< double > & overlap, Tensor< double > & fock, Tensor< double > & evals, const double thresh_degenerate)
compute the unitary transformation that diagonalizes the fock matrix
Parameters
[in] world the world
[in] overlap the overlap matrix of the orbitals
[in,out] fock the fock matrix; diagonal upon exit
[out] evals the orbital energies
[in] thresh_degenerate threshold for orbitals being degenerate
Returns
the unitary matrix U: U^T F U = evals
References madness::_(), madness::copy(), madness::inner(), max, madness::mxm(), print(), madness::ResponseParameters::print_level(), madness::Tensor< T >::ptr(), q(), r_params, madness::World::rank(), madness::Tensor< T >::scale(), sigma, madness::svd(), madness::swap(), madness::sygv(), and madness::transpose().
Referenced by diagonalize_CIS_guess(), and diagonalizeFockMatrix().
GetConjugateTransitionDensities()
std::vector< real_function_3d > TDDFT::GetConjugateTransitionDensities (World & world, const std::vector< real_function_3d > & orbitals, const response_space & f)
References f, and m.
Referenced by GetConjugateWxcOnFDensities().
GetConjugateWxcOnFDensities()
std::vector< real_function_3d > TDDFT::GetConjugateWxcOnFDensities (World & world, const std::vector< real_function_3d > & orbitals, const response_space & f)
References create_XCOperator(), f, GetConjugateTransitionDensities(), ground_orbitals, r_params, xc, and madness::ResponseParameters::xc().
GetFullResponseTransformation()
Tensor< double > TDDFT::GetFullResponseTransformation (World & world, Tensor< double > & S, Tensor< double > & A, Tensor< double > & evals, const double thresh)
SVD on overlap matrix S S=UsVT S, U, s , VT
l_vecs_s(m,1)
Returns
Tensor<double>
References madness::_(), madness::abs(), madness::copy(), madness::ResponseParameters::dconv(), molresponse::end_timer(), madness::ggevp(), madness::imag(), madness::inner(), m, MADNESS_ASSERT, max, madness::mxm(), omega, print(), madness::ResponseParameters::print_level(), madness::Tensor< T >::ptr(), q(), r_params, madness::World::rank(), madness::real(), madness::Tensor< T >::scale(), sigma, sort_eigenvalues(), molresponse::start_timer(), madness::svd(), madness::swap(), and madness::transpose().
Referenced by diagonalizeFullResponseMatrix().
GetTransitionDensities()
std::vector< real_function_3d > TDDFT::GetTransitionDensities (World & world, const std::vector< real_function_3d > & orbitals, const response_space & f)
References f, and m.
Referenced by GetWxcOnFDensities().
GetWxcOnFDensities()
std::vector< real_function_3d > TDDFT::GetWxcOnFDensities (World & world, const std::vector< real_function_3d > & orbitals, const response_space & f)
References create_XCOperator(), f, GetTransitionDensities(), ground_orbitals, r_params, xc, and madness::ResponseParameters::xc().
gram_schmidt() [1/2]
response_space TDDFT::gram_schmidt (World & world, response_space & f)
References f, madness::gaxpy(), madness::inner(), k, m, madness::detail::norm(), madness::norm2(), madness::scale(), and madness::response_space::truncate_rf().
Referenced by iterate_guess(), solve_excited_states(), and update_x_space_excited().
gram_schmidt() [2/2]
void TDDFT::gram_schmidt (World & world, response_space & f, response_space & g)
References f, g(), madness::gaxpy(), madness::inner(), k, m, madness::detail::norm(), and madness::scale().
initial_load_bal()
void TDDFT::initial_load_bal (World & world)
References madness::LoadBalanceDeux< NDIM >::add_tree(), madness::LoadBalanceDeux< NDIM >::load_balance(), madness::ResponseParameters::loadbalparts(), potential_manager, r_params, vnuc(), and madness::ResponseParameters::vnucextra().
Referenced by main().
initialize_excited_json()
void TDDFT::initialize_excited_json ()
iterate_excited()
void TDDFT::iterate_excited (World & world, X_space & Chi)
References madness::Tensor< T >::absmax(), analysis(), analyze_vectors(), b, madness::ResponseParameters::calc_type(), Chi, create_XCOperator(), madness::ResponseParameters::dconv(), madness::do_vtk_plots(), molresponse::end_timer(), excited_to_json(), madness::Tensor< T >::fill(), g_params, madness::QCCalculationParametersBase::get(), ground_orbitals, j_molresponse, madness::ResponseParameters::kain(), madness::ResponseParameters::L(), load_balance(), m, make_density(), make_ground_density(), max, madness::Tensor< T >::max(), madness::ResponseParameters::maxiter(), madness::ResponseParameters::maxrotn(), madness::ResponseParameters::maxsub(), molecule, madness::Molecule::natom(), madness::response_space::norm2(), madness::norm2s_T(), madness::ResponseParameters::num_orbitals(), madness::X_space::num_states(), madness::ResponseParameters::num_states(), omega, madness::ResponseParameters::plot(), madness::ResponseParameters::plot_all_orbitals(), PlotGroundandResponseOrbitals(), print(), madness::ResponseParameters::print_level(), r_params, madness::World::rank(), rho0, rho_omega, madness::ResponseParameters::save(), save(), madness::ResponseParameters::save_file(), sort(), molresponse::start_timer(), madness::ResponseParameters::tda(), update_x_space_excited(), madness::wall_time(), madness::X_space::X, xc, madness::ResponseParameters::xc(), and madness::X_space::Y.
Referenced by solve_excited_states().
iterate_freq2()
void TDDFT::iterate_freq2 (World & world)
References madness::abs(), madness::Tensor< T >::absmax(), b, Chi, compute_and_print_polarizability(), madness::X_space::copy(), create_XCOperator(), madness::ResponseParameters::dconv(), madness::do_vtk_plots(), molresponse::end_timer(), madness::Tensor< T >::fill(), frequency_to_json(), g_params, madness::QCCalculationParametersBase::get(), ground_energies, ground_orbitals, madness::inner(), j_molresponse, madness::ResponseParameters::kain(), madness::ResponseParameters::L(), load_balance(), m, make_bsh_operators_response(), make_ground_density(), max, madness::Tensor< T >::max(), madness::ResponseParameters::maxiter(), madness::ResponseParameters::maxrotn(), madness::ResponseParameters::maxsub(), molecule, madness::Molecule::natom(), madness::response_space::norm2(), madness::norm2s_T(), madness::ResponseParameters::num_orbitals(), madness::X_space::num_states(), madness::ResponseParameters::num_states(), omega, madness::ResponseParameters::omega(), madness::ResponseParameters::plot(), madness::ResponseParameters::plot_all_orbitals(), PlotGroundandResponseOrbitals(), PQ, print(), madness::ResponseParameters::print_level(), r_params, madness::World::rank(), rho0, rho_omega, madness::ResponseParameters::save(), save(), madness::ResponseParameters::save_file(), molresponse::start_timer(), transition_density(), update_x_space_response(), madness::wall_time(), madness::X_space::X, xc, madness::ResponseParameters::xc(), and madness::X_space::Y.
Referenced by solve_response_states().
iterate_guess()
void TDDFT::iterate_guess (World & world, X_space & guesses)
References madness::LoadBalanceDeux< NDIM >::add_tree(), madness::apply(), apply_shift(), Compute_Lambda_X(), Compute_Theta_X(), madness::copy(), create_bsh_operators(), create_shift(), create_XCOperator(), deflateGuesses(), molresponse::end_timer(), gram_schmidt(), ground_energies, ground_orbitals, madness::ResponseParameters::guess_max_iter(), k, madness::ResponseParameters::lo(), madness::LoadBalanceDeux< NDIM >::load_balance(), m, mask, normalize(), madness::ResponseParameters::num_orbitals(), madness::ResponseParameters::num_states(), omega, print(), madness::ResponseParameters::print_level(), r_params, madness::World::rank(), rho_omega, madness::World::size(), madness::response_space::size(), molresponse::start_timer(), madness::ResponseParameters::tda(), transition_densityTDA(), madness::response_space::truncate_rf(), V(), madness::wall_time(), madness::X_space::X, xc, and madness::ResponseParameters::xc().
Referenced by solve_excited_states().
kain_x_space_update()
X_space TDDFT::kain_x_space_update (World & world, const X_space & temp, const X_space & res, NonLinearXsolver & kain_x_space, std::vector< X_vector > & Xvector, std::vector< X_vector > & Xresidual)
Computes the the X_space kain update.
Parameters
world
temp
res
kain_x_space
Xvector
Xresidual
Returns
X_space
References b, madness::copy(), molresponse::end_timer(), m, madness::X_space::num_orbitals(), madness::X_space::num_states(), molresponse::start_timer(), madness::X_space::X, and madness::X_space::Y.
Referenced by update_x_space_excited(), and update_x_space_response().
load()
void TDDFT::load (World & world, const std::string & name)
References madness::ResponseParameters::archive(), Chi, madness::WorldGopInterface::fence(), madness::World::gop, madness::ResponseParameters::num_orbitals(), madness::ResponseParameters::num_states(), omega, r_params, madness::ResponseParameters::tda(), madness::X_space::X, and madness::X_space::Y.
Referenced by solve_excited_states(), and solve_response_states().
load_balance()
void TDDFT::load_balance (World & world, vecfuncT rho_omega, X_space Chi, const X_space & Chi_old)
References madness::LoadBalanceDeux< NDIM >::add_tree(), Chi, molresponse::end_timer(), madness::WorldGopInterface::fence(), madness::World::gop, madness::LoadBalanceDeux< NDIM >::load_balance(), madness::ResponseParameters::loadbalparts(), madness::ResponseParameters::omega(), potential_manager, madness::print_meminfo(), r_params, madness::World::rank(), rho_omega, madness::World::size(), madness::response_space::size(), madness::response_space::size_orbitals(), molresponse::start_timer(), madness::ResponseParameters::vnucextra(), madness::X_space::X, and madness::X_space::Y.
Referenced by iterate_excited(), and iterate_freq2().
make_bsh_operators_response()
std::vector< poperatorT > TDDFT::make_bsh_operators_response (World & world, double & shift, double & omega) const
References madness::BSHOperatorPtr3D(), molresponse::end_timer(), ground_energies, madness::ResponseParameters::lo(), mu, omega, p, madness::ResponseParameters::print_level(), r_params, shift, and molresponse::start_timer().
Referenced by iterate_freq2().
make_density() [1/2]
vecfuncT TDDFT::make_density (World & world)
make_density() [2/2]
vecfuncT TDDFT::make_density (World & world, X_space & Chi, std::string calc_type)
References Chi, molresponse::end_timer(), madness::WorldGopInterface::fence(), madness::World::gop, ground_orbitals, madness::print_meminfo(), madness::World::rank(), rho_omega, molresponse::start_timer(), transition_density(), transition_densityTDA(), madness::X_space::X, and madness::X_space::Y.
Referenced by iterate_excited().
make_ground_density()
functionT TDDFT::make_ground_density (World & world, const vecfuncT & v)
References madness::compress(), madness::WorldGopInterface::fence(), g_params, GroundStateCalculation::get_occ(), madness::World::gop, rho, and square().
Referenced by iterate_excited(), iterate_freq2(), and set_protocol().
make_nuclear_potential()
void TDDFT::make_nuclear_potential (World & world)
References madness::ResponseParameters::core_type(), molecule, potential_manager, r_params, and molresponse::start_timer().
Referenced by main().
matrix_exponential()
Tensor< double > TDDFT::matrix_exponential (const Tensor< double > & A)
References B, e(), madness::inner(), k, MADNESS_ASSERT, madness::Tensor< T >::normf(), madness::scale(), and madness::Tensor< T >::scale().
normalize() [1/3]
void TDDFT::normalize (World & world, response_space & f) static
References f, madness::inner(), and madness::detail::norm().
Referenced by create_nwchem_guess(), diagonalizeFockMatrix(), diagonalizeFullResponseMatrix(), iterate_guess(), solve_excited_states(), and update_x_space_excited().
normalize() [2/3]
void TDDFT::normalize (World & world, response_space & f, response_space & g)
References f, g(), madness::inner(), madness::detail::norm(), and madness::scale().
normalize() [3/3]
void TDDFT::normalize (World & world, X_space & Chi)
References Chi, madness::inner(), madness::detail::norm(), madness::X_space::num_states(), madness::X_space::X, and madness::X_space::Y.
orbital_load_balance()
void TDDFT::orbital_load_balance (World & world, vecfuncT & psi0, vecfuncT & psi0_copy, X_space & Chi, X_space & Chi_copy)
References madness::LoadBalanceDeux< NDIM >::add_tree(), Chi, madness::X_space::copy(), madness::copy(), molresponse::end_timer(), madness::WorldGopInterface::fence(), madness::World::gop, ground_orbitals, madness::LoadBalanceDeux< NDIM >::load_balance(), madness::ResponseParameters::loadbalparts(), m, madness::ResponseParameters::num_orbitals(), madness::ResponseParameters::num_states(), psi0(), r_params, madness::World::size(), molresponse::start_timer(), madness::X_space::X, and madness::X_space::Y.
Referenced by compute_gamma_full(), compute_gamma_static(), and compute_gamma_tda().
output_json()
void TDDFT::output_json () const
References j_molresponse.
Referenced by main().
plot_excited_states()
void TDDFT::plot_excited_states (World & world, size_t iteration, response_space & x_response, response_space & y_response, ResponseParameters const & r_params, GroundStateCalculation const & g_params)
References b, d(), madness::dir, madness::WorldGopInterface::fence(), madness::World::gop, TDDFT::plotCoords::hi, madness::ResponseParameters::L(), TDDFT::plotCoords::lo, m, madness::plot_line(), r_params, and madness::response_space::size().
PlotGroundandResponseOrbitals()
void TDDFT::PlotGroundandResponseOrbitals (World & world, size_t iteration, response_space & x_response, response_space & y_response, ResponseParameters const & r_params, GroundStateCalculation const & g_params)
References b, d(), madness::dir, madness::dot(), madness::WorldGopInterface::fence(), madness::World::gop, ground_orbitals, TDDFT::plotCoords::hi, madness::ResponseParameters::L(), TDDFT::plotCoords::lo, m, madness::plot_line(), r_params, rho0, madness::response_space::size(), and transition_density().
Referenced by iterate_excited(), and iterate_freq2().
polarizability()
Tensor< double > TDDFT::polarizability ()
References Chi, madness::inner(), and PQ.
Referenced by main().
print_norms()
void TDDFT::print_norms (World & world, response_space function)
References f, print(), and madness::World::rank().
Referenced by create_trial_functions(), and create_trial_functions2().
print_residual_norms()
void TDDFT::print_residual_norms (World & world, X_space & old_Chi, bool compute_y, size_t iteration)
References m, madness::norm2(), madness::X_space::num_states(), print(), madness::ResponseParameters::print_level(), r_params, madness::World::rank(), madness::X_space::X, and madness::X_space::Y.
PrintPolarizabilityAnalysis()
void TDDFT::PrintPolarizabilityAnalysis (World & world, const Tensor< double > polar_tensor)
References omega, pow(), print(), madness::World::rank(), madness::syev(), and V().
Referenced by main().
PrintResponseVectorNorms()
void TDDFT::PrintResponseVectorNorms (World & world, response_space f, std::string fname)
References f, print(), and madness::World::rank().
Referenced by compute_gamma_tda().
PrintRFExpectation()
void TDDFT::PrintRFExpectation (World & world, response_space f, response_space g, std::string fname, std::string gname)
References f, g(), print(), and madness::World::rank().
Referenced by compute_gamma_tda().
project_ao_basis()
vecfuncT TDDFT::project_ao_basis (World & world, const AtomicBasisSet & aobasis)
References aobasis, at_nbf, at_to_bf, madness::AtomicBasisSet::atoms_to_bfn(), molecule, and project_ao_basis_only().
Referenced by analyze_vectors().
project_ao_basis_only()
vecfuncT TDDFT::project_ao_basis_only (World & world, const AtomicBasisSet & aobasis, const Molecule & molecule)
References aobasis, madness::WorldGopInterface::fence(), madness::AtomicBasisSet::get_atomic_basis_function(), madness::World::gop, molecule, madness::AtomicBasisSet::nbf(), madness::normalize(), and madness::truncate().
Referenced by project_ao_basis().
PropertyRHS()
response_space TDDFT::PropertyRHS (World & world, PropertyBase & p) const
References molresponse::end_timer(), madness::WorldGopInterface::fence(), madness::World::gop, ground_orbitals, madness::ResponseParameters::lo(), madness::mul(), madness::norm2(), PropertyBase::num_operators, madness::ResponseParameters::num_orbitals(), PropertyBase::operator_vector, p, print(), madness::ResponseParameters::print_level(), r_params, madness::reconstruct(), molresponse::start_timer(), and madness::truncate().
Referenced by solve_response_states().
save()
void TDDFT::save (World & world, const std::string & name)
References madness::ResponseParameters::archive(), Chi, madness::ResponseParameters::num_orbitals(), madness::ResponseParameters::num_states(), omega, r_params, madness::ResponseParameters::tda(), madness::X_space::X, and madness::X_space::Y.
Referenced by iterate_excited(), iterate_freq2(), and solve_excited_states().
select_active_subspace()
void TDDFT::select_active_subspace (World & world)
References act_ground_energies, act_num_orbitals, act_orbitals, active, madness::ResponseParameters::e_range_hi(), madness::ResponseParameters::e_range_lo(), g_params, GroundStateCalculation::get_energies(), ground_orbitals, MADNESS_ASSERT, madness::ResponseParameters::num_orbitals(), print(), madness::ResponseParameters::print_level(), r_params, and madness::World::rank().
select_functions()
response_space TDDFT::select_functions (World & world, response_space & f, Tensor< double > & energies, size_t k, size_t print_level)
References f, k, print(), madness::World::rank(), and madness::response_space::truncate_rf().
Referenced by solve_excited_states().
set_protocol()
template<std::size_t NDIM> void TDDFT::set_protocol (World & world, double thresh)
References madness::CoulombOperatorPtr(), coulop, madness::ResponseParameters::dconv(), madness::ResponseParameters::dconv_set(), e(), f, gradop, ground_orbitals, k, madness::ResponseParameters::k(), madness::ResponseParameters::lo(), make_ground_density(), mask, mask3(), max, NDIM, print(), r_params, madness::World::rank(), rho0, madness::QCCalculationParametersBase::set_derived_value(), madness::set_thresh(), thresh, and vtol.
Referenced by main().
SetPlotCoord()
plotCoords TDDFT::SetPlotCoord (size_t i, double Lp)
simple_spherical_harmonics()
std::map< std::vector< int >, real_function_3d > TDDFT::simple_spherical_harmonics (World & world, int n)
References c, m, madness::Function< T, NDIM >::norm2(), and madness::Function< T, NDIM >::scale().
solid_harmonics()
std::map< std::vector< int >, real_function_3d > TDDFT::solid_harmonics (World & world, int n)
References c, madness::copy(), kronecker(), m, and pow().
Referenced by create_trial_functions().
solve_excited_states()
void TDDFT::solve_excited_states (World & world)
References madness::LoadBalanceDeux< NDIM >::add_tree(), check_k(), Chi, madness::X_space::clear(), create_nwchem_guess(), create_random_guess(), create_trial_functions(), create_trial_functions2(), madness::do_vtk_plots(), molresponse::end_timer(), gram_schmidt(), ground_orbitals, madness::ResponseParameters::guess_xyz(), iterate_excited(), iterate_guess(), j_molresponse, k, madness::ResponseParameters::L(), load(), madness::LoadBalanceDeux< NDIM >::load_balance(), molecule, normalize(), madness::ResponseParameters::num_orbitals(), madness::ResponseParameters::num_states(), madness::ResponseParameters::nwchem(), omega, madness::ResponseParameters::plot(), madness::ResponseParameters::plot_data(), madness::ResponseParameters::plot_initial(), madness::ResponseParameters::plot_l(), madness::ResponseParameters::plot_pts(), print(), madness::ResponseParameters::protocol(), r_params, madness::ResponseParameters::random(), madness::World::rank(), madness::ResponseParameters::restart(), madness::ResponseParameters::restart_file(), madness::ResponseParameters::save(), save(), madness::ResponseParameters::save_file(), select_functions(), madness::World::size(), madness::response_space::size(), sort(), square(), molresponse::start_timer(), transition_density(), madness::X_space::X, and madness::X_space::Y.
Referenced by main().
solve_response_states()
void TDDFT::solve_response_states (World & world)
References check_k(), Chi, madness::response_space::copy(), madness::ResponseParameters::dipole(), madness::do_vtk_plots(), molresponse::end_timer(), g_params, ground_orbitals, iterate_freq2(), j_molresponse, madness::ResponseParameters::L(), load(), MADNESS_EXCEPTION, GroundStateCalculation::molecule(), molecule, madness::response_space::norm2(), madness::ResponseParameters::nuclear(), madness::ResponseParameters::num_orbitals(), madness::ResponseParameters::num_states(), madness::ResponseParameters::order2(), madness::ResponseParameters::order3(), p, madness::ResponseParameters::plot(), madness::ResponseParameters::plot_data(), madness::ResponseParameters::plot_initial(), madness::ResponseParameters::plot_l(), madness::ResponseParameters::plot_pts(), PQ, print(), PropertyRHS(), madness::ResponseParameters::protocol(), r_params, madness::World::rank(), madness::ResponseParameters::restart(), madness::ResponseParameters::restart_file(), madness::QCCalculationParametersBase::set_derived_value(), square(), molresponse::start_timer(), thresh, transition_density(), madness::X_space::X, and madness::X_space::Y.
Referenced by main().
sort() [1/2]
void TDDFT::sort (World & world, Tensor< double > & vals, response_space & f)
References madness::copy(), e(), f, k, and madness::Tensor< T >::ptr().
Referenced by iterate_excited(), and solve_excited_states().
sort() [2/2]
void TDDFT::sort (World & world, Tensor< double > & vals, X_space & f)
References madness::copy(), e(), f, k, madness::Tensor< T >::ptr(), madness::X_space::X, and madness::X_space::Y.
sort_eigenvalues()
Tensor< int > TDDFT::sort_eigenvalues (World & world, Tensor< double > & vals, Tensor< double > & vecs)
References madness::_(), madness::copy(), e(), and k.
Referenced by diagonalizeFockMatrix(), and GetFullResponseTransformation().
transform()
response_space TDDFT::transform (World & world, response_space & f, Tensor< double > & U)
References f, madness::gaxpy(), madness::response_space::push_back(), and madness::response_space::truncate_rf().
Referenced by diagonalizeFockMatrix(), and diagonalizeFullResponseMatrix().
transition_density()
std::vector< real_function_3d > TDDFT::transition_density (World & world, std::vector< real_function_3d > & orbitals, response_space & x, response_space & y)
References b, madness::dot(), madness::WorldGopInterface::fence(), madness::World::gop, m, madness::response_space::size(), madness::truncate(), and madness::response_space::truncate_rf().
Referenced by create_fxc(), iterate_freq2(), make_density(), PlotGroundandResponseOrbitals(), solve_excited_states(), and solve_response_states().
transition_densityTDA()
std::vector< real_function_3d > TDDFT::transition_densityTDA (World & world, std::vector< real_function_3d > const & orbitals, response_space & x)
References b, madness::dot(), madness::WorldGopInterface::fence(), madness::World::gop, ground_orbitals, m, madness::response_space::size(), madness::truncate(), and madness::response_space::truncate_rf().
Referenced by iterate_guess(), and make_density().
unaugment()
void TDDFT::unaugment (World & world, X_space & Chi, X_space & old_Chi, X_space & Lambda_X, X_space & last_Lambda_X, Tensor< double > & omega, Tensor< double > & S_x, Tensor< double > & A_x, Tensor< double > & old_S, Tensor< double > & old_A, size_t num_states, size_t iter, size_t print_level)
References Chi, madness::response_space::copy(), molresponse::end_timer(), omega, madness::response_space::pop_back(), molresponse::start_timer(), and madness::X_space::X.
Referenced by deflateTDA().
unaugment_full()
void TDDFT::unaugment_full (World & world, X_space & Chi, X_space & old_Chi, X_space & Lambda_X, X_space & last_Lambda_X, Tensor< double > & omega, Tensor< double > & S_x, Tensor< double > & A_x, Tensor< double > & old_S, Tensor< double > & old_A, size_t num_states, size_t iter, size_t print_level)
References Chi, madness::X_space::copy(), molresponse::end_timer(), omega, madness::X_space::pop_back(), print(), molresponse::start_timer(), madness::X_space::X, and madness::X_space::Y.
Referenced by deflateFull().
update_x_space_excited()
void TDDFT::update_x_space_excited (World & world, X_space & old_Chi, X_space & Chi, X_space & old_Lambda_X, X_space & residuals, XCOperator< double, 3 > & xc, QProjector< double, 3 > & projector, Tensor< double > & omega, NonLinearXsolver & kain_x_space, std::vector< X_vector > & Xvector, std::vector< X_vector > & Xresidual, Tensor< double > & energy_residuals, Tensor< double > & old_energy, Tensor< double > & bsh_residualsX, Tensor< double > & bsh_residualsY, Tensor< double > & S, Tensor< double > & old_S, Tensor< double > & A, Tensor< double > & old_A, size_t iteration, Tensor< double > & maxrotn)
References bsh_update_excited(), madness::ResponseParameters::calc_type(), Chi, Compute_Lambda_X(), compute_new_omegas_transform(), compute_residual(), Compute_Theta_X(), madness::X_space::copy(), gram_schmidt(), madness::ResponseParameters::kain(), kain_x_space_update(), m, madness::ResponseParameters::maxiter(), normalize(), madness::X_space::num_states(), omega, print(), r_params, madness::ResponseParameters::tda(), madness::response_space::truncate_rf(), madness::X_space::X, x_space_step_restriction(), xc, and madness::X_space::Y.
Referenced by iterate_excited().
update_x_space_response()
void TDDFT::update_x_space_response (World & world, X_space & Chi, X_space & residual, XCOperator< double, 3 > & xc, std::vector< poperatorT > & bsh_x_ops, std::vector< poperatorT > & bsh_y_ops, QProjector< double, 3 > & projector, double & x_shifts, double & omega_n, NonLinearXsolver & kain_x_space, std::vector< X_vector > Xvector, std::vector< X_vector > Xresidual, Tensor< double > & bsh_residualsX, Tensor< double > & bsh_residualsY, size_t iteration, Tensor< double > & maxrotn)
References bsh_update_response(), madness::ResponseParameters::calc_type(), Chi, compute_and_print_polarizability(), compute_residual(), Compute_Theta_X(), madness::X_space::copy(), madness::response_space::copy(), madness::ResponseParameters::kain(), kain_x_space_update(), m, madness::X_space::num_states(), madness::ResponseParameters::omega(), PQ, print(), madness::ResponseParameters::print_level(), r_params, madness::response_space::truncate_rf(), madness::X_space::X, x_space_step_restriction(), xc, and madness::X_space::Y.
Referenced by iterate_freq2().
vector_stats()
void TDDFT::vector_stats (const std::vector< double > & v, double & rms, double & maxabsval) const
References std::abs().
Referenced by compute_residual(), and do_step_restriction().
vector_stats_new()
void TDDFT::vector_stats_new (const Tensor< double > v, double & rms, double & maxabsval) const
References madness::Tensor< T >::max().
Referenced by do_step_restriction().
x_space_step_restriction()
void TDDFT::x_space_step_restriction (World & world, X_space & old_Chi, X_space & temp, bool restrict_y, Tensor< double > & maxrotn)
References b, do_step_restriction(), molresponse::end_timer(), m, madness::X_space::num_states(), print(), molresponse::start_timer(), madness::X_space::X, and madness::X_space::Y.
Referenced by update_x_space_excited(), and update_x_space_response().
Member Data Documentation
act_ground_energies
Tensor<double> TDDFT::act_ground_energies
Referenced by select_active_subspace().
act_num_orbitals
unsigned int TDDFT::act_num_orbitals
Referenced by select_active_subspace().
act_orbitals
std::vector<real_function_3d> TDDFT::act_orbitals
Referenced by select_active_subspace().
active
std::vector<int> TDDFT::active
Referenced by select_active_subspace().
Chi
X_space TDDFT::Chi
Referenced by analysis(), augment(), augment_full(), bsh_update_excited(), bsh_update_response(), check_k(), compute_and_print_polarizability(), compute_F0X(), compute_gamma_full(), compute_gamma_static(), compute_gamma_tda(), Compute_Lambda_X(), compute_new_omegas_transform(), Compute_Theta_X(), compute_V0X(), deflateFull(), deflateGuesses(), deflateTDA(), diagonalizeFockMatrix(), diagonalizeFullResponseMatrix(), iterate_excited(), iterate_freq2(), load(), load_balance(), make_density(), normalize(), orbital_load_balance(), polarizability(), save(), solve_excited_states(), solve_response_states(), TDDFT(), unaugment(), unaugment_full(), update_x_space_excited(), and update_x_space_response().
coulop
poperatorT TDDFT::coulop
Referenced by compute_gamma_full(), compute_gamma_static(), compute_gamma_tda(), compute_V0X(), exchange(), and set_protocol().
e_residuals
Tensor<double> TDDFT::e_residuals
g_params
GroundStateCalculation TDDFT::g_params
Referenced by check_k(), create_nwchem_guess(), CreateGroundHamiltonian(), iterate_excited(), iterate_freq2(), make_ground_density(), select_active_subspace(), solve_response_states(), and TDDFT().
gradop
std::vector<std::shared_ptr<real_derivative_3d> > TDDFT::gradop
Referenced by set_protocol().
ground_energies
Tensor<double> TDDFT::ground_energies
Referenced by bsh_update_excited(), iterate_freq2(), iterate_guess(), make_bsh_operators_response(), and TDDFT().
ground_orbitals
std::vector<real_function_3d> TDDFT::ground_orbitals
Referenced by analysis(), check_k(), compute_gamma_full(), compute_gamma_static(), compute_gamma_tda(), compute_V0X(), Coulomb(), create_fxc(), create_nwchem_guess(), create_XCOperator(), CreateXCDerivative(), exchange(), GetConjugateWxcOnFDensities(), GetWxcOnFDensities(), iterate_excited(), iterate_freq2(), iterate_guess(), make_density(), orbital_load_balance(), PlotGroundandResponseOrbitals(), PropertyRHS(), select_active_subspace(), set_protocol(), solve_excited_states(), solve_response_states(), TDDFT(), and transition_densityTDA().
ham_no_diag
Tensor<double> TDDFT::ham_no_diag
Referenced by Compute_Theta_X(), and CreateGroundHamiltonian().
hamiltonian
Tensor<double> TDDFT::hamiltonian
Referenced by check_k(), Compute_Lambda_X(), and CreateGroundHamiltonian().
j_molresponse
nlohmann::json TDDFT::j_molresponse
Referenced by iterate_excited(), iterate_freq2(), main(), output_json(), solve_excited_states(), solve_response_states(), and TDDFT().
mask
functionT TDDFT::mask
Referenced by add_randomness(), bsh_update_excited(), check_k(), create_random_guess(), iterate_guess(), set_protocol(), and TDDFT().
molecule
Molecule TDDFT::molecule
Referenced by analyze_vectors(), create_random_guess(), iterate_excited(), iterate_freq2(), main(), make_nuclear_potential(), project_ao_basis(), project_ao_basis_only(), solve_excited_states(), solve_response_states(), and TDDFT().
omega
Tensor<double> TDDFT::omega
Referenced by analysis(), bsh_update_excited(), compute_new_omegas_transform(), create_bsh_operators(), create_shift(), create_shift_target(), CreateBSHOperatorPropertyVector(), deflateFull(), deflateGuesses(), deflateTDA(), diagonalize_CIS_guess(), diagonalizeFullResponseMatrix(), excited_to_json(), frequency_to_json(), GetFullResponseTransformation(), iterate_excited(), iterate_freq2(), iterate_guess(), load(), make_bsh_operators_response(), PrintPolarizabilityAnalysis(), save(), solve_excited_states(), unaugment(), unaugment_full(), and update_x_space_excited().
p
PropertyBase TDDFT::p
Referenced by apply_shift(), create_bsh_operators(), create_shift(), create_shift_target(), CreateBSHOperatorPropertyVector(), expectation(), make_bsh_operators_response(), PropertyRHS(), and solve_response_states().
potential_manager
std::shared_ptr<PotentialManager> TDDFT::potential_manager
Referenced by compute_V0X(), initial_load_bal(), load_balance(), and make_nuclear_potential().
PQ
X_space TDDFT::PQ
Referenced by bsh_update_response(), check_k(), compute_and_print_polarizability(), iterate_freq2(), polarizability(), solve_response_states(), TDDFT(), and update_x_space_response().
r_params
ResponseParameters TDDFT::r_params
Referenced by analysis(), analyze_vectors(), apply_shift(), bsh_update_excited(), bsh_update_response(), check_k(), compute_F0X(), compute_gamma_full(), compute_gamma_static(), compute_gamma_tda(), Compute_Lambda_X(), compute_new_omegas_transform(), compute_residual(), Compute_Theta_X(), compute_V0X(), Coulomb(), create_bsh_operators(), create_fxc(), create_nwchem_guess(), CreateBSHOperatorPropertyVector(), CreateGroundHamiltonian(), CreateXCDerivative(), deflateFull(), deflateGuesses(), deflateTDA(), diagonalize_CIS_guess(), diagonalizeFockMatrix(), diagonalizeFullResponseMatrix(), do_step_restriction(), get_fock_transformation(), GetConjugateWxcOnFDensities(), GetFullResponseTransformation(), GetWxcOnFDensities(), initial_load_bal(), iterate_excited(), iterate_freq2(), iterate_guess(), load(), load_balance(), main(), make_bsh_operators_response(), make_nuclear_potential(), orbital_load_balance(), plot_excited_states(), PlotGroundandResponseOrbitals(), print_residual_norms(), PropertyRHS(), save(), select_active_subspace(), set_protocol(), solve_excited_states(), solve_response_states(), TDDFT(), update_x_space_excited(), and update_x_space_response().
rho
density_vector TDDFT::rho
Referenced by Coulomb(), create_XCOperator(), make_ground_density(), and TDDFT().
rho0
functionT TDDFT::rho0
Referenced by compute_V0X(), iterate_excited(), iterate_freq2(), PlotGroundandResponseOrbitals(), and set_protocol().
rho_omega
vecfuncT TDDFT::rho_omega
Referenced by compute_gamma_full(), compute_gamma_static(), compute_gamma_tda(), iterate_excited(), iterate_freq2(), iterate_guess(), load_balance(), and make_density().
stored_potential
response_space TDDFT::stored_potential
Referenced by check_k(), and CreateGroundHamiltonian().
stored_v_coul
real_function_3d TDDFT::stored_v_coul
Referenced by check_k(), compute_V0X(), and CreateGroundHamiltonian().
stored_v_nuc
real_function_3d TDDFT::stored_v_nuc
Referenced by check_k(), compute_V0X(), and CreateGroundHamiltonian().
vtol
double TDDFT::vtol
Referenced by analyze_vectors(), and set_protocol().
xcf
XCfunctional TDDFT::xcf
Referenced by compute_gamma_full(), compute_gamma_static(), compute_gamma_tda(), and compute_V0X().
The documentation for this class was generated from the following files:
TDDFT.h
calc_runner.cc
iter_freq2.cc
iterate_excited.cc
iterate_gamma.cc
Lambda_X.cc
TDDFT.cc
Theta_X.cc