MADNESS: dataloadbal.cc File Reference
dataloadbal.cc File Reference
Illustrates how to use static data/load balancing of functions.
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/mra/vmra.h>
#include <madness/mra/lbdeux.h>
#include <madness/constants.h>
Classes
class Gaussian< T, NDIM >
struct LBCost
Functions
int main (int argc, char **argv)
real_functor_3d random_gaussian ()
void test (World &world, bool doloadbal=false)
Variables
static const int NFUNC = 4
Detailed Description
Illustrates how to use static data/load balancing of functions.
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::finalize(), madness::initialize(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_apply_randomize(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_project_randomize(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), madness::startup(), and test().
random_gaussian()
real_functor_3d random_gaussian ()
References e(), Gaussian, madness::FunctionDefaults< NDIM >::get_cell(), lo, madness::constants::pi, pow(), and madness::RandomValue< double >().
Referenced by test().
test()
void test (World & world, bool doloadbal = false)
References madness::LoadBalanceDeux< NDIM >::add_tree(), madness::apply(), madness::CoulombOperator(), madness::default_random_generator, e(), madness::f, madness::WorldGopInterface::fence(), madness::World::gop, madness::LoadBalanceDeux< NDIM >::load_balance(), loadbal(), NFUNC, op(), random_gaussian(), madness::World::rank(), madness::FunctionDefaults< NDIM >::redistribute(), madness::Random::setstate(), madness::truncate(), and madness::wall_time().
Referenced by madness::FunctionImpl< Q, NDIM >::autorefine_square_test(), madness::GFit< T, NDIM >::bsh_fit(), madness::GFit< T, NDIM >::bsh_fit_ndim(), check(), check_vector(), compare(), madness::SimpleCache< madness::SeparatedConvolutionData< Q, NDIM >, 2 *NDIM >::getptr(), madness::PNO::guess_virtuals(), main(), madness::detail::adqtest::runtest(), madness::GFit< T, NDIM >::slater_fit(), madness::CC2::solve(), test_converged_function(), test_convergence(), and testbsh().
Variable Documentation
NFUNC
const int NFUNC = 4 static
Referenced by test().