MADNESS: global_functions.cc File Reference
global_functions.cc File Reference
#include "global_functions.h"
#include <memory>
#include <string>
#include <vector>
#include "response_parameters.h"
Functions
CalcParams initialize_calc_params (World &world, std::string input_file)
void print_molecule (World &world, const GroundStateCalculation &g_params)
Function Documentation
initialize_calc_params()
CalcParams initialize_calc_params (World & world, std::string input_file)
References molecule, madness::Molecule::print(), and madness::commandlineparser::set_keyval().
Referenced by main(), and TEST_CASE().
print_molecule()
void print_molecule (World & world, const GroundStateCalculation & g_params)
References madness::atomic_number_to_symbol(), madness::Molecule::get_atoms(), GroundStateCalculation::molecule(), print(), and madness::World::rank().