MADNESS: hatom_1d.cc File Reference
hatom_1d.cc File Reference
Solves the Schrodinger equation for the 1-d hydrogen atom.
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
Functions
static double guess (const coord_1d &r)
void iterate (World &world, real_function_1d &V, real_function_1d &psi, double &eps)
int main (int argc, char **argv)
static double V (const coord_1d &r)
Variables
static const long k = 6
static const double L = 100
static const double thresh = 1e-4
Detailed Description
Solves the Schrodinger equation for the 1-d hydrogen atom.
The Hartree-Fock wave function is computed for the hydrogen atom in one dimension without using symmetry.
Function Documentation
guess()
static double guess (const coord_1d & r) static
Referenced by main().
iterate()
void iterate (World & world, real_function_1d & V, real_function_1d & psi, double & eps)
References e(), madness::inner(), madness::detail::norm(), madness::Function< T, NDIM >::norm2(), op(), madness::print(), psi(), madness::World::rank(), madness::Function< T, NDIM >::scale(), and V().
Referenced by main().
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, guess(), madness::initialize(), madness::inner(), iterate(), k, L, lo, madness::plot_line(), potential(), madness::print(), psi(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::square(), madness::startup(), thresh, and V().
V()
static double V (const coord_1d & r) static
References e().
Referenced by iterate(), and main().
Variable Documentation
k
const long k = 6 static
Referenced by main().
L
const double L = 100 static
Referenced by main().
thresh
const double thresh = 1e-4 static
Referenced by main().