MADNESS: heat2.cc File Reference
heat2.cc File Reference
Example Green function for the 3D heat equation with a linear term.
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/constants.h>
Classes
class uexact
struct unaryexp< T, NDIM >
Functions
int main (int argc, char **argv)
static double uinitial (const coord_3d &r)
static double Vp (const coord_3d &r)
Variables
static const double alpha = 1.9
static const double c = 2.0
static const long k = 8
static const double L = 20
static const double thresh = 1e-6
static const double tstep = 0.1
static const double VVV = 0.2
Detailed Description
Example Green function for the 3D heat equation with a linear term.
Function Documentation
main()
int main (int argc, char ** argv)
References c, SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), madness::finalize(), G, madness::World::gop, madness::initialize(), k, L, madness::Function< T, NDIM >::norm2(), madness::constants::pi, pow(), madness::print(), madness::World::rank(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), thresh, madness::Function< T, NDIM >::trace(), madness::Function< T, NDIM >::truncate(), tstep, u(), uexact(), uinitial(), madness::Function< T, NDIM >::unaryop(), and Vp().
uinitial()
static double uinitial (const coord_3d & r) static
References alpha, madness::constants::pi, and pow().
Referenced by main().
Vp()
static double Vp (const coord_3d & r) static
References VVV.
Referenced by main().
Variable Documentation
alpha
const double alpha = 1.9 static
Referenced by uexact::operator()(), and uinitial().
c
const double c = 2.0 static
Referenced by main(), and uexact::operator()().
k
const long k = 8 static
Referenced by main().
L
const double L = 20 static
Referenced by main().
thresh
const double thresh = 1e-6 static
Referenced by main().
tstep
const double tstep = 0.1 static
Referenced by main().
VVV
const double VVV = 0.2 static
Referenced by uexact::operator()(), and Vp().