MADNESS: helium_exact.cc File Reference
helium_exact.cc File Reference
Solves the two-particle system exactly.
#include <madness/world/info.h>
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/mra/funcplot.h>
#include <madness/mra/lbdeux.h>
#include <iostream>
#include <madness/chem/SCF.h>
#include <madness/chem/nemo.h>
#include <madness/chem/correlationfactor.h>
#include <madness/chem/electronic_correlation_factor.h>
#include <madness/chem/commandlineparser.h>
Macros
#define WITH_G12
Typedefs
typedef std::shared_ptr< NuclearCorrelationFactor > ncf_ptr
Functions
real_function_6d apply_U_ecf (World &world, const real_function_6d &psi, const CorrelationFactor2 &ecf)
real_function_6d apply_U_mix (World &world, const real_function_6d &psi, const CorrelationFactor2 &ecf, const ncf_ptr &ncf)
real_function_6d apply_U_ncf (World &world, const real_function_6d &psi, const ncf_ptr &ncf)
real_function_6d apply_V (World &world, const real_function_6d &psi, const SCF &calc)
double compute_energy (World &world, const real_function_6d &psi, const CorrelationFactor2 &ecf, const ncf_ptr &ncf, const real_function_3d &vnuc)
compute the energy using the reconstructed wave function
double compute_energy_with_U (World &world, const real_function_6d &psi, const CorrelationFactor2 &ecf, const ncf_ptr &ncf, const real_function_6d &twoVpsi)
compute the energy using the regularization
real_function_6d compute_R2f2_psi (World &world, const real_function_6d &psi, const CorrelationFactor2 &ecf, const ncf_ptr &ncf)
compute R_12^2f_12^2|psi>
void load (World &world, real_function_6d &f, std::string filename)
int main (int argc, char **argv)
real_function_6d reconstruct_psi (World &world, const real_function_6d &psi, const CorrelationFactor2 &ecf, const ncf_ptr &ncf)
reconstruct the full wave function
void save (World &world, const real_function_6d &f, std::string filename)
void test_U_el (World &world, const real_function_6d &psi, const CorrelationFactor2 &ecf)
the electronic U potential is U -1/r12 = f^-1 [T, f] = f^-1 T f - T
Variables
static double bsh_eps = 1.e-8
static double lo = 1.e-8
Detailed Description
Solves the two-particle system exactly.
Macro Definition Documentation
WITH_G12
#define WITH_G12
Typedef Documentation
ncf_ptr
typedef std::shared_ptr<NuclearCorrelationFactor> ncf_ptr
Function Documentation
apply_U_ecf()
real_function_6d apply_U_ecf (World & world, const real_function_6d & psi, const CorrelationFactor2 & ecf)
References psi().
Referenced by main(), and test_U_el().
apply_U_mix()
real_function_6d apply_U_mix (World & world, const real_function_6d & psi, const CorrelationFactor2 & ecf, const ncf_ptr & ncf)
References axis, bsh_eps, madness::copy(), madness::Function< T, NDIM >::fill_tree(), madness::CompositeFactory< T, NDIM, MDIM >::g12(), madness::CompositeFactory< T, NDIM, MDIM >::ket(), lo, madness::SeparatedConvolution< Q, NDIM >::modified(), madness::print(), psi(), madness::World::rank(), madness::Function< T, NDIM >::truncate(), madness::CompositeFactory< T, NDIM, MDIM >::V_for_particle1(), and madness::CompositeFactory< T, NDIM, MDIM >::V_for_particle2().
Referenced by main().
apply_U_ncf()
real_function_6d apply_U_ncf (World & world, const real_function_6d & psi, const ncf_ptr & ncf)
References axis, bsh_eps, madness::copy(), madness::Function< T, NDIM >::fill_tree(), madness::CompositeFactory< T, NDIM, MDIM >::ket(), lo, madness::SeparatedConvolution< Q, NDIM >::modified(), madness::print(), psi(), madness::r2(), madness::World::rank(), madness::Function< T, NDIM >::reduce_rank(), madness::truncate(), madness::Function< T, NDIM >::truncate(), madness::CompositeFactory< T, NDIM, MDIM >::V_for_particle1(), and madness::CompositeFactory< T, NDIM, MDIM >::V_for_particle2().
Referenced by main().
apply_V()
real_function_6d apply_V (World & world, const real_function_6d & psi, const SCF & calc)
References bsh_eps, madness::copy(), madness::CompositeFactory< T, NDIM, MDIM >::ket(), lo, madness::SeparatedConvolution< Q, NDIM >::modified(), madness::SCF::potentialmanager, psi(), madness::r2(), madness::CompositeFactory< T, NDIM, MDIM >::V_for_particle1(), madness::CompositeFactory< T, NDIM, MDIM >::V_for_particle2(), and vnuc().
compute_energy()
double compute_energy (World & world, const real_function_6d & psi, const CorrelationFactor2 & ecf, const ncf_ptr & ncf, const real_function_3d & vnuc)
compute the energy using the reconstructed wave function
Returns
the energy expectation value <E> = < Psi | H | Psi >
References bsh_eps, madness::copy(), madness::TwoElectronFactory::dcut(), madness::Function< T, NDIM >::fill_tree(), madness::CompositeFactory< T, NDIM, MDIM >::g12(), madness::inner(), madness::CompositeFactory< T, NDIM, MDIM >::ket(), lo, madness::SeparatedConvolution< Q, NDIM >::modified(), madness::detail::norm(), madness::Function< T, NDIM >::norm2(), madness::CompositeFactory< T, NDIM, MDIM >::particle1(), madness::CompositeFactory< T, NDIM, MDIM >::particle2(), madness::print(), psi(), R2, madness::World::rank(), reconstruct_psi(), madness::Function< T, NDIM >::square(), madness::truncate(), madness::CompositeFactory< T, NDIM, MDIM >::V_for_particle1(), madness::CompositeFactory< T, NDIM, MDIM >::V_for_particle2(), and vnuc().
Referenced by main().
compute_energy_with_U()
double compute_energy_with_U (World & world, const real_function_6d & psi, const CorrelationFactor2 & ecf, const ncf_ptr & ncf, const real_function_6d & twoVpsi)
compute the energy using the regularization
Returns
the energy expectation value <E> = < psi | R2f2 (T+U) | psi >
References compute_R2f2_psi(), energy, madness::inner(), madness::detail::norm(), madness::print(), psi(), and madness::World::rank().
Referenced by main().
compute_R2f2_psi()
real_function_6d compute_R2f2_psi (World & world, const real_function_6d & psi, const CorrelationFactor2 & ecf, const ncf_ptr & ncf)
compute R_12^2f_12^2|psi>
References bsh_eps, madness::copy(), madness::Function< T, NDIM >::fill_tree(), madness::CompositeFactory< T, NDIM, MDIM >::g12(), madness::inner(), madness::CompositeFactory< T, NDIM, MDIM >::ket(), lo, madness::SeparatedConvolution< Q, NDIM >::modified(), madness::print(), psi(), madness::World::rank(), madness::CompositeFactory< T, NDIM, MDIM >::V_for_particle1(), and madness::CompositeFactory< T, NDIM, MDIM >::V_for_particle2().
Referenced by compute_energy_with_U().
load()
void load (World & world, real_function_6d & f, std::string filename)
References madness::f, and madness::filename.
main()
int main (int argc, char ** argv)
References apply_U_ecf(), apply_U_mix(), apply_U_ncf(), madness::arg(), bsh_eps, madness::Function< T, NDIM >::clear(), SafeMPI::COMM_WORLD, compute_energy(), compute_energy_with_U(), madness::copy(), madness::SeparatedConvolution< Q, NDIM >::destructive(), energy, madness::archive::BaseParallelArchive< BinaryFstreamInputArchive >::exists(), madness::WorldGopInterface::fence(), madness::filename, madness::finalize(), madness::Nemo::get_calc(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::info::git_commit(), madness::World::gop, madness::hartree_product(), madness::initialize(), madness::inner(), lo, madness::load(), madness::NemoBase::ncf, madness::detail::norm(), madness::Function< T, NDIM >::norm2(), param, madness::print(), madness::Function< T, NDIM >::print_size(), psi(), madness::World::rank(), madness::save(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_tensor_type(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::World::size(), madness::startup(), test_U_el(), madness::Function< T, NDIM >::truncate(), madness::TT_2D, madness::Nemo::value(), vnuc(), and madness::wall_time().
reconstruct_psi()
real_function_6d reconstruct_psi (World & world, const real_function_6d & psi, const CorrelationFactor2 & ecf, const ncf_ptr & ncf)
reconstruct the full wave function
Psi from the regularized wave function and the correlation factors
References bsh_eps, madness::copy(), madness::Function< T, NDIM >::fill_tree(), madness::CompositeFactory< T, NDIM, MDIM >::g12(), madness::inner(), madness::CompositeFactory< T, NDIM, MDIM >::ket(), lo, madness::SeparatedConvolution< Q, NDIM >::modified(), madness::print(), psi(), madness::World::rank(), madness::CompositeFactory< T, NDIM, MDIM >::V_for_particle1(), and madness::CompositeFactory< T, NDIM, MDIM >::V_for_particle2().
Referenced by compute_energy().
save()
void save (World & world, const real_function_6d & f, std::string filename)
References madness::f, and madness::filename.
test_U_el()
void test_U_el (World & world, const real_function_6d & psi, const CorrelationFactor2 & ecf)
the electronic U potential is U -1/r12 = f^-1 [T, f] = f^-1 T f - T
References apply_U_ecf(), bsh_eps, madness::copy(), madness::TwoElectronFactory::dcut(), madness::Function< T, NDIM >::fill_tree(), madness::g, madness::CompositeFactory< T, NDIM, MDIM >::g12(), madness::inner(), madness::CompositeFactory< T, NDIM, MDIM >::ket(), lo, madness::SeparatedConvolution< Q, NDIM >::modified(), madness::Function< T, NDIM >::norm2(), madness::print(), psi(), madness::World::rank(), and u().
Referenced by main().
Variable Documentation
bsh_eps
double bsh_eps = 1.e-8 static
Referenced by apply_U_mix(), apply_U_ncf(), apply_V(), compute_energy(), compute_R2f2_psi(), madness::CC2::iterate_pair(), madness::CC2::iterate_singles(), main(), reconstruct_psi(), and test_U_el().
lo
double lo = 1.e-8 static
Referenced by madness::adq(), madness::adq1(), APPLY(), madness::SCF::APPLY(), madness::APPLY(), madness::TDHF::apply_G(), apply_U_mix(), apply_U_ncf(), apply_V(), madness::FunctionImpl< Q, NDIM >::autorefine_square_test(), madness::GFit< T, NDIM >::bsh_fit(), madness::GFit< T, NDIM >::bsh_fit_ndim(), madness::GFit< T, NDIM >::BSHFit(), madness::BSHOperator(), madness::BSHOperator3D(), madness::BSHOperatorPtr(), madness::BSHOperatorPtr3D(), madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::MacroTaskExchangeSimple::compute_batch_in_asymmetric_matrix(), madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::MacroTaskExchangeSimple::compute_diagonal_batch_in_symmetric_matrix(), compute_energy(), madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::MacroTaskExchangeSimple::compute_offdiagonal_batch_in_symmetric_matrix(), compute_R2f2_psi(), madness::GFit< T, NDIM >::CoulombFit(), madness::CoulombOperator(), madness::CoulombOperatorPtr(), cplxfunc0(), cplxfunc1(), cplxfunc2(), cplxvec0(), cplxvec1(), cplxvec2(), TDDFT::create_bsh_operators(), TDDFT::CreateBSHOperatorPropertyVector(), TDDFT::diagonalize_CIS_guess(), madness::do_adq(), Plotter::dolineplot(), draw_line(), madness::F12Potentials::F12Potentials(), madness::TDHF::TDHFParameters::get_ccc_parameters(), madness::GradBSHOperator(), madness::GradCoulombOperator(), madness::GradSlaterOperator(), madness::SCF::group_orbital_sets(), madness::DQueue< madness::PoolTaskInterface * >::grow(), madness::TDHF::initialize(), K(), madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::K_large_memory(), madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::K_macrotask_efficient(), madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::K_small_memory(), madness::Localizer::localize_new(), main(), make_bsh_operators(), make_pts(), SurfaceMoleculeInteraction::make_surfcharge(), madness::SeparatedConvolution< T, NDIM >::make_tt_representation(), mask3(), madness::mask3(), MolecularNuclearPotentialFunctor2::MolecularNuclearPotentialFunctor2(), refop::operator()(), madness::orthonormalize_canonical(), madness::PeriodicBSHOp(), madness::PeriodicBSHOperator3D(), madness::PeriodicBSHOperatorPtr3D(), madness::PeriodicBSHOpPtr(), madness::PeriodicCoulombOp(), madness::PeriodicCoulombOpPtr(), madness::PeriodicHFExchangeOperator(), SurfaceMoleculeInteraction::perturbed_molecular_pot(), plot(), madness::XCfunctional::plot(), madness::plot_line(), Calculation::plot_p(), madness::plot_plane(), Calculation::plot_z(), madness::PM_q(), random_gaussian(), RandomGaussian(), realfunc0(), realfunc1(), realfunc2(), realvec0(), realvec1(), realvec2(), reconstruct_psi(), madness::Coulomb< double, 3 >::reset_poisson_operator_ptr(), madness::SCF::rotate_subspace(), madness::Nemo::rotate_subspace(), madness::ThreadBase::set_affinity(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionFunctorInterface< double_complex, 3 >::set_length_scale(), madness::FunctionDefaults< NDIM >::set_length_scale(), madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::set_parameters(), madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::set_poisson(), madness::Random::setstate(), madness::GFit< T, NDIM >::slater_fit(), madness::SlaterF12Operator(), madness::SlaterF12OperatorPtr(), madness::GFit< T, NDIM >::SlaterFit(), madness::SlaterOperator(), madness::SlaterOperatorPtr(), solve(), madness::SystolicMatrixAlgorithm< double >::SystolicMatrixAlgorithm(), test(), test_apply_push_1d(), test_exchange(), test_gconv(), test_gence2(), test_modified(), test_overlap(), test_recursive_application(), test_U_el(), madness::FunctionImpl< Q, NDIM >::tnorm(), madness::NuclearCorrelationFactor::U1X_functor::U1X_functor(), and madness::NuclearCorrelationFactor::U2X_functor::U2X_functor().