MADNESS: madness_catch_main.cc File Reference
madness_catch_main.cc File Reference
#include "madness/external/catch/catch.hpp"
#include "madness/chem/SCF.h"
#include "madness/world/worldmem.h"
Macros
#define CATCH_CONFIG_RUNNER
Functions
int main (int argc, char *argv[])
Macro Definition Documentation
CATCH_CONFIG_RUNNER
#define CATCH_CONFIG_RUNNER
Function Documentation
main()
int main (int argc, char * argv[])
References e(), error(), initialize(), and print().