MADNESS: mcpfit.cc File Reference
mcpfit.cc File Reference
fitting parameters of Model Core Potential
#include <madness/mra/mra.h>
#include <madness/tensor/solvers.h>
#include <madness/chem/corepotential.h>
#include <iostream>
#include <iomanip>
#include <set>
#include <cstdio>
Classes
struct Calculation
struct CalculationParameters
struct CoreFittingTarget
class CoreOrbitalFunctor
class CorePotentialFunctor
class GaussianFunctor
class MySteepestDescent
class NcOverR
class PotentialBasisFunctor
class RadiusFunctor
class RadiusSquareFunctor
Typedefs
typedef Vector< double, 3 > coordT
typedef FunctionFactory< double, 3 > factoryT
typedef Function< double, 3 > functionT
typedef std::shared_ptr< FunctionFunctorInterface< double, 3 > > functorT
typedef SeparatedConvolution< double, 3 > operatorT
typedef std::shared_ptr< WorldDCPmapInterface< Key< 3 > > > pmapT
typedef std::shared_ptr< operatorT> poperatorT
typedef Tensor< double > tensorT
typedef vector< functionT > vecfuncT
Functions
void END_TIMER (World &world, const char *msg)
int main (int argc, char **argv)
double mask1 (double x)
double mask3 (const coordT &ruser)
void print (const tensorT &t)
tensorT Q3 (const tensorT &s)
Given overlap matrix, return rotation with 3rd order error to orthonormalize the vectors.
static double radius_function (double rsq)
void START_TIMER (World &world)
static vector< double > tensor2vec (const tensorT &t)
static tensorT vec2tensor (const vector< double > &v)
Variables
static double sss
static double ttt
Detailed Description
fitting parameters of Model Core Potential
Typedef Documentation
coordT
typedef Vector<double,3> coordT
factoryT
typedef FunctionFactory<double,3> factoryT
functionT
typedef Function<double,3> functionT
functorT
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > functorT
operatorT
typedef SeparatedConvolution<double,3> operatorT
pmapT
typedef std::shared_ptr< WorldDCPmapInterface< Key<3> > > pmapT
poperatorT
typedef std::shared_ptr<operatorT> poperatorT
tensorT
typedef Tensor<double> tensorT
vecfuncT
typedef vector<functionT> vecfuncT
Function Documentation
END_TIMER()
void END_TIMER (World & world, const char * msg)
References madness::cpu_time(), madness::World::rank(), madness::sss, madness::ttt, and madness::wall_time().
main()
int main (int argc, char ** argv)
References madness::CorePotential::alpha, Calculation::amo, Calculation::atn, b, Calculation::bmo, Calculation::calc_optimal_coeffs(), SafeMPI::COMM_WORLD, Calculation::compute_residuals(), Calculation::corepot, e(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::CorePotentialManager::get_potential(), madness::World::gop, madness::initialize(), Calculation::nbeta, MySteepestDescent::optimize(), Calculation::param, madness::print(), madness::print_stats(), madness::r2(), Calculation::spin_restricted, madness::startup(), tensor2vec(), Calculation::vamo, Calculation::vbmo, and vec2tensor().
mask1()
double mask1 (double x) inline
mask3()
double mask3 (const coordT & ruser)
References lo, madness::mask1(), and madness::user_to_sim().
Referenced by TDDFT::set_protocol(), and TDDFT::TDDFT().
print()
void print (const tensorT & t)
Referenced by TDDFT::analysis(), TDDFT::analyze_vectors(), TDDFT::augment(), TDDFT::augment_full(), TDDFT::bsh_update_excited(), TDDFT::calculate_energy_update(), TDDFT::compute_and_print_polarizability(), TDDFT::compute_F0X(), TDDFT::compute_gamma_full(), TDDFT::compute_gamma_tda(), TDDFT::Compute_Lambda_X(), TDDFT::compute_new_omegas_transform(), TDDFT::compute_residual(), TDDFT::Compute_Theta_X(), TDDFT::compute_V0X(), TDDFT::create_bsh_operators(), TDDFT::create_nwchem_guess(), TDDFT::create_random_guess(), TDDFT::create_shift(), TDDFT::create_shift_target(), TDDFT::create_trial_functions(), TDDFT::create_trial_functions2(), TDDFT::CreateGroundHamiltonian(), TDDFT::deflateFull(), TDDFT::deflateGuesses(), TDDFT::deflateTDA(), TDDFT::diagonalize_CIS_guess(), TDDFT::diagonalizeFockMatrix(), TDDFT::diagonalizeFullResponseMatrix(), DipoleVector::DipoleVector(), TDDFT::do_step_restriction(), doplotptk(), TDDFT::get_fock_transformation(), TDDFT::GetFullResponseTransformation(), TDDFT::iterate_excited(), TDDFT::iterate_freq2(), TDDFT::iterate_guess(), main(), NuclearVector::NuclearVector(), opt(), madness::QCCalculationParametersBase::print(), print_molecule(), TDDFT::print_norms(), TDDFT::print_residual_norms(), TDDFT::PrintPolarizabilityAnalysis(), TDDFT::PrintResponseVectorNorms(), TDDFT::PrintRFExpectation(), TDDFT::PropertyRHS(), madness::QCCalculationParametersBase::read_internal(), TDDFT::select_active_subspace(), TDDFT::select_functions(), TDDFT::set_protocol(), TDDFT::solve_excited_states(), TDDFT::solve_response_states(), TDDFT::TDDFT(), TEST_CASE(), madness::QCCalculationParametersBase::try_setting_user_defined_value(), TDDFT::unaugment_full(), Subspace::update_subspace(), TDDFT::update_x_space_excited(), TDDFT::update_x_space_response(), and TDDFT::x_space_step_restriction().
Q3()
tensorT Q3 (const tensorT & s)
Given overlap matrix, return rotation with 3rd order error to orthonormalize the vectors.
References madness::Tensor< T >::gaxpy(), madness::inner(), and madness::Tensor< T >::scale().
radius_function()
static double radius_function (double rsq) inline static
Referenced by RadiusFunctor::operator()().
START_TIMER()
void START_TIMER (World & world)
References madness::cpu_time(), madness::WorldGopInterface::fence(), madness::World::gop, madness::sss, madness::ttt, and madness::wall_time().
tensor2vec()
static vector<double> tensor2vec (const tensorT & t) static
Referenced by Calculation::calc_optimal_coeffs(), CoreFittingTarget::gradient(), main(), Calculation::update(), and CoreFittingTarget::value().
vec2tensor()
static tensorT vec2tensor (const vector< double > & v) static
Referenced by main(), and Calculation::update().
Variable Documentation
sss
double sss static
ttt
double ttt static