MADNESS: molresponse.cc File Reference
molresponse.cc File Reference
Molecular Response DFT code.
#include <madness/chem/SCF.h>
#include <madness/world/worldmem.h>
#include "ResponseExceptions.hpp"
#include "TDDFT.h"
#include "molresponse/density.h"
Functions
int main (int argc, char **argv)
Detailed Description
Molecular Response DFT code.
Function Documentation
main()
int main (int argc, char ** argv)
References alpha, SafeMPI::COMM_WORLD, madness::ResponseParameters::dipole(), e(), molresponse::end_timer(), madness::error(), madness::ResponseParameters::excited_state(), madness::WorldGopInterface::fence(), madness::finalize(), madness::ResponseParameters::first_order(), madness::World::gop, TDDFT::initial_load_bal(), madness::initialize(), initialize_calc_params(), TDDFT::j_molresponse, TDDFT::make_nuclear_potential(), molecule, TDDFT::molecule, TDDFT::output_json(), TDDFT::polarizability(), madness::print(), madness::QCCalculationParametersBase::print(), madness::Molecule::print(), madness::print_meminfo(), madness::print_stats(), TDDFT::PrintPolarizabilityAnalysis(), TDDFT::r_params, madness::World::rank(), madness::ResponseParameters::second_order(), set_density_type(), madness::FunctionDefaults< NDIM >::set_pmap(), TDDFT::set_protocol(), madness::World::size(), TDDFT::solve_excited_states(), TDDFT::solve_response_states(), molresponse::start_timer(), madness::startup(), and madness::ResponseParameters::to_json().