MADNESS: molresponse Namespace Reference
molresponse Namespace Reference
Functions
void end_timer (World &world, const char *msg)
void end_timer (World &world, const char *msg)
double pop (std::vector< double > &v)
void start_timer (World &world)
void start_timer (World &world)
Variables
static std::vector< double > sss
static std::vector< double > ttt
Function Documentation
end_timer() [1/2]
void molresponse::end_timer (World & world, const char * msg)
end_timer() [2/2]
void molresponse::end_timer (World & world, const char * msg)
References cpu_time(), MADNESS_CHECK, pop(), madness::World::rank(), sss, ttt, and madness::wall_time().
Referenced by TDDFT::analyze_vectors(), TDDFT::apply_shift(), TDDFT::augment(), TDDFT::augment_full(), TDDFT::bsh_update_response(), TDDFT::compute_F0X(), TDDFT::compute_gamma_full(), TDDFT::compute_gamma_static(), TDDFT::compute_gamma_tda(), TDDFT::compute_residual(), TDDFT::compute_V0X(), TDDFT::create_bsh_operators(), TDDFT::create_shift(), TDDFT::create_shift_target(), TDDFT::CreateBSHOperatorPropertyVector(), TDDFT::CreateGroundHamiltonian(), TDDFT::diagonalize_CIS_guess(), TDDFT::diagonalizeFockMatrix(), TDDFT::diagonalizeFullResponseMatrix(), TDDFT::GetFullResponseTransformation(), TDDFT::iterate_excited(), TDDFT::iterate_freq2(), TDDFT::iterate_guess(), TDDFT::kain_x_space_update(), TDDFT::load_balance(), main(), TDDFT::make_bsh_operators_response(), TDDFT::make_density(), TDDFT::orbital_load_balance(), TDDFT::PropertyRHS(), TDDFT::solve_excited_states(), TDDFT::solve_response_states(), TDDFT::TDDFT(), TEST_CASE(), TDDFT::unaugment(), TDDFT::unaugment_full(), and TDDFT::x_space_step_restriction().
pop()
double molresponse::pop (std::vector< double > & v)
Referenced by end_timer().
start_timer() [1/2]
void molresponse::start_timer (World & world)
start_timer() [2/2]
void molresponse::start_timer (World & world)
References cpu_time(), madness::WorldGopInterface::fence(), madness::World::gop, sss, ttt, and madness::wall_time().
Referenced by TDDFT::analyze_vectors(), TDDFT::apply_shift(), TDDFT::augment(), TDDFT::augment_full(), TDDFT::bsh_update_response(), TDDFT::compute_F0X(), TDDFT::compute_gamma_full(), TDDFT::compute_gamma_static(), TDDFT::compute_gamma_tda(), TDDFT::compute_residual(), TDDFT::compute_V0X(), TDDFT::create_bsh_operators(), TDDFT::create_shift(), TDDFT::create_shift_target(), TDDFT::CreateBSHOperatorPropertyVector(), TDDFT::CreateGroundHamiltonian(), TDDFT::diagonalize_CIS_guess(), TDDFT::diagonalizeFockMatrix(), TDDFT::diagonalizeFullResponseMatrix(), TDDFT::GetFullResponseTransformation(), TDDFT::iterate_excited(), TDDFT::iterate_freq2(), TDDFT::iterate_guess(), TDDFT::kain_x_space_update(), TDDFT::load_balance(), main(), TDDFT::make_bsh_operators_response(), TDDFT::make_density(), TDDFT::make_nuclear_potential(), TDDFT::orbital_load_balance(), TDDFT::PropertyRHS(), TDDFT::solve_excited_states(), TDDFT::solve_response_states(), TDDFT::TDDFT(), TEST_CASE(), TDDFT::unaugment(), TDDFT::unaugment_full(), and TDDFT::x_space_step_restriction().
Variable Documentation
sss
std::vector<double> molresponse::sss static
Referenced by end_timer(), and start_timer().
ttt
std::vector<double> molresponse::ttt static
Referenced by end_timer(), and start_timer().