MADNESS: preal.cc File Reference
preal.cc File Reference
#include <madness/mra/mra.h>
#include <madness/tensor/solvers.h>
#include <madness/external/tinyxml/tinyxml.h>
#include <madness/world/worldmem.h>
#include <madness/chem/molecule.h>
#include <madness/chem/molecularbasis.h>
#include <madness/chem/xcfunctional.h>
#include <madness/chem/gth_pseudopotential.h>
#include "wst_functional.h"
Classes
class AtomicBasisFunctor< Q >
struct BoysLocalization
class DipoleFunctor
A MADNESS functor to compute either x, y, or z.
class MiniDFT
class MolecularGuessDensityFunctor
class MolecularPotentialFunctor
class NuclearDensityFunctor
Typedefs
typedef std::shared_ptr< real_convolution_3d > poperatorT
Functions
void drot (long n, double *MADNESS_RESTRICT a, double *MADNESS_RESTRICT b, double s, double c, long inc)
Simple (?) version of BLAS-1 DROT(N, DX, INCX, DY, INCY, DC, DS)
void drot3 (long n, double *MADNESS_RESTRICT a, double *MADNESS_RESTRICT b, double s, double c, long inc)
int main (int argc, char **argv)
Variables
static std::vector< int > at_nbf
static std::vector< int > at_to_bf
static const double twopi = 2.0*constants::pi
Typedef Documentation
poperatorT
typedef std::shared_ptr<real_convolution_3d> poperatorT
Function Documentation
drot()
void drot (long n, double *MADNESS_RESTRICT a, double *MADNESS_RESTRICT b, double s, double c, long inc)
Simple (?) version of BLAS-1 DROT(N, DX, INCX, DY, INCY, DC, DS)
References a, aa, b, and c.
Referenced by madness::SystolicPMOrbitalLocalize::localize_PM_ij(), main(), and BoysLocalization::operator()().
drot3()
void drot3 (long n, double *MADNESS_RESTRICT a, double *MADNESS_RESTRICT b, double s, double c, long inc)
References a, b, and c.
Referenced by BoysLocalization::operator()().
main()
int main (int argc, char ** argv)
References madness::Molecule::add_atom(), SafeMPI::COMM_WORLD, MiniDFT::doit(), e(), madness::initialize(), kwavelet, L, molecule, madness::Molecule::orient(), madness::Molecule::print(), madness::startup(), thresh, and truncate_mode.
Variable Documentation
at_nbf
std::vector<int> at_nbf static
Referenced by madness::AtomicBasisSet::atoms_to_bfn(), AtomicBasisSet::atoms_to_bfn(), madness::distributed_localize_PM(), MiniDFT::makeao(), and TDDFT::project_ao_basis().
at_to_bf
std::vector<int> at_to_bf static
Referenced by madness::AtomicBasisSet::atoms_to_bfn(), AtomicBasisSet::atoms_to_bfn(), madness::distributed_localize_PM(), MiniDFT::makeao(), and TDDFT::project_ao_basis().
twopi
const double twopi = 2.0*constants::pi static
Referenced by phi_bsh_func3d(), phi_initial_guess3D(), rho_bsh_func3d(), V_cosine1D(), V_cosine3D(), and V_cosine3D_sep().