MADNESS: ResponseBase.cpp File Reference
ResponseBase.cpp File Reference
#include "ResponseBase.hpp"
Functions
vecfuncT K (vecfuncT &ket, vecfuncT &bra, vecfuncT &vf)
void PlotGroundDensityVTK (World &world, const ResponseBase &calc)
response_space T (World &world, response_space &f)
Function Documentation
K()
vecfuncT K (vecfuncT & ket, vecfuncT & bra, vecfuncT & vf)
Important this is
was vtol
was vtol
References madness::apply(), madness::CoulombOperatorPtr(), madness::gaxpy(), madness::FunctionDefaults< NDIM >::get_thresh(), lo, madness::mul_sparse(), madness::reconstruct(), and madness::truncate().
PlotGroundDensityVTK()
void PlotGroundDensityVTK (World & world, const ResponseBase & calc)
References madness::do_vtk_plots(), molecule, madness::print(), and madness::square().
T()
response_space T (World & world, response_space & f)
References madness::apply(), and madness::f.