MADNESS: madness::X_space_allocator Struct Reference
madness::X_space_allocator Struct Reference
#include <x_space.h>
Public Member Functions
X_space_allocator (World &world, size_t n_orbtials)
X_vector operator() ()
X_space_allocator operator= (const X_space_allocator &other)
Public Attributes
const size_t n_orbtials
const size_t n_states
World & world
Constructor & Destructor Documentation
X_space_allocator()
madness::X_space_allocator::X_space_allocator (World & world, size_t n_orbtials) inline
Referenced by operator=().
Member Function Documentation
operator()()
X_vector madness::X_space_allocator::operator() () inline
References n_orbtials, madness::print(), and world.
operator=()
X_space_allocator madness::X_space_allocator::operator= (const X_space_allocator & other) inline
References n_orbtials, world, and X_space_allocator().
Member Data Documentation
n_orbtials
const size_t madness::X_space_allocator::n_orbtials
Referenced by operator()(), and operator=().
n_states
const size_t madness::X_space_allocator::n_states
world
World& madness::X_space_allocator::world
Referenced by operator()(), and operator=().
The documentation for this struct was generated from the following file:
x_space.h