MADNESS: madness::LoadBalanceDeux< NDIM >::add_op< T, costT > Struct Template Reference
madness::LoadBalanceDeux< NDIM >::add_op< T, costT > Struct Template Reference
Public Member Functions
add_op (LoadBalanceDeux *lb, const costT &costfn)
void operator() (const keyT &key, const FunctionNode< T, NDIM > &node) const
Public Attributes
const costT & costfn
LoadBalanceDeux * lb
Constructor & Destructor Documentation
add_op()
template<std::size_t NDIM> template<typename T , typename costT > madness::LoadBalanceDeux< NDIM >::add_op< T, costT >::add_op (LoadBalanceDeux * lb, const costT & costfn) inline
Member Function Documentation
operator()()
template<std::size_t NDIM> template<typename T , typename costT > void madness::LoadBalanceDeux< NDIM >::add_op< T, costT >::operator() (const keyT & key, const FunctionNode< T, NDIM > & node) const inline
References madness::LBNodeDeux< NDIM >::add(), madness::LoadBalanceDeux< NDIM >::add_op< T, costT >::costfn, madness::FunctionNode< T, NDIM >::has_children(), madness::WorldContainer< keyT, valueT, hashfunT >::is_local(), madness::LoadBalanceDeux< NDIM >::add_op< T, costT >::lb, madness::WorldContainer< keyT, valueT, hashfunT >::send(), madness::WorldContainer< keyT, valueT, hashfunT >::task(), and madness::LoadBalanceDeux< NDIM >::tree.
Member Data Documentation
costfn
template<std::size_t NDIM> template<typename T , typename costT > const costT& madness::LoadBalanceDeux< NDIM >::add_op< T, costT >::costfn
Referenced by madness::LoadBalanceDeux< NDIM >::add_op< T, costT >::operator()().
lb
template<std::size_t NDIM> template<typename T , typename costT > LoadBalanceDeux* madness::LoadBalanceDeux< NDIM >::add_op< T, costT >::lb
Referenced by madness::LoadBalanceDeux< NDIM >::add_op< T, costT >::operator()().
The documentation for this struct was generated from the following file:
lbdeux.h