MADNESS: madness::FunctionImpl< T, NDIM >::do_average Struct Reference
madness::FunctionImpl< T, NDIM >::do_average Struct Reference
"put" this on g
#include <funcimpl.h>
Public Types
typedef Range< typename dcT::const_iterator > rangeT
Public Member Functions
do_average ()
do_average (implT &g)
bool operator() (typename rangeT::iterator &it) const
iterator it points to this
template<typename Archive >
void serialize (const Archive &ar)
Public Attributes
implT * g
Detailed Description
template<typename T, std::size_t NDIM>
struct madness::FunctionImpl< T, NDIM >::do_average
"put" this on g
Member Typedef Documentation
rangeT
template<typename T , std::size_t NDIM> typedef Range<typename dcT::const_iterator> madness::FunctionImpl< T, NDIM >::do_average::rangeT
Constructor & Destructor Documentation
do_average() [1/2]
template<typename T , std::size_t NDIM> madness::FunctionImpl< T, NDIM >::do_average::do_average () inline
do_average() [2/2]
template<typename T , std::size_t NDIM> madness::FunctionImpl< T, NDIM >::do_average::do_average (implT & g) inline
Member Function Documentation
operator()()
template<typename T , std::size_t NDIM> bool madness::FunctionImpl< T, NDIM >::do_average::operator() (typename rangeT::iterator & it) const inline
iterator it points to this
References madness::FunctionNode< T, NDIM >::coeff(), madness::WorldContainer< keyT, valueT, hashfunT >::find(), madness::FunctionImpl< T, NDIM >::do_average::g, madness::FunctionImpl< T, NDIM >::get_coeffs(), madness::FunctionNode< T, NDIM >::has_coeff(), and madness::WorldContainer< keyT, valueT, hashfunT >::replace().
serialize()
template<typename T , std::size_t NDIM> template<typename Archive > void madness::FunctionImpl< T, NDIM >::do_average::serialize (const Archive & ar) inline
Member Data Documentation
g
template<typename T , std::size_t NDIM> implT* madness::FunctionImpl< T, NDIM >::do_average::g
Referenced by madness::FunctionImpl< T, NDIM >::do_average::operator()().
The documentation for this struct was generated from the following file:
funcimpl.h