MADNESS: madness::ResponseParameters Struct Reference
madness::ResponseParameters Struct Reference
#include <response_parameters.h>
Public Member Functions
ResponseParameters ()
ResponseParameters (const ResponseParameters &other)=default
std::string archive () const
std::string calc_type () const
std::string core_type () const
std::string d2_types () const
double dconv () const
bool dconv_set () const
bool dipole () const
bool e_range () const
double e_range_hi () const
double e_range_lo () const
double econv () const
bool excited_state () const
bool first_order () const
bool first_run () const
size_t guess_max_iter () const
bool guess_xyz () const
int k () const
bool kain () const
double L () const
size_t larger_subspace () const
double lo () const
bool load_density () const
std::string load_density_file () const
int loadbalparts () const
std::string local () const
std::string localize () const
size_t maxiter () const
double maxrotn () const
size_t maxsub () const
bool nuclear () const
size_t num_orbitals () const
size_t num_states () const
bool nwchem () const
std::string nwchem_dir () const
double omega () const
bool order2 () const
bool order3 () const
bool plot () const
bool plot_all_orbitals () const
std::vector< double > plot_cell () const
std::vector< int > plot_data () const
bool plot_initial () const
double plot_l () const
size_t plot_pts () const
bool plot_range () const
int print_level () const
bool property () const
std::vector< double > protocol () const
bool random () const
virtual void read_input_and_commandline_options (World &world, const commandlineparser &parser, const std::string tag)
bool restart () const
std::string restart_file () const
bool save () const
bool save_density () const
std::string save_density_file () const
std::string save_file () const
bool second_order () const
void set_derived_values (World &world, Molecule molecule)
void set_ground_state_calculation_data (GroundStateCalculation g_params)
bool spinrestricted () const
bool store_potential () const
bool tda () const
bool third_order () const
void to_json (nlohmann::json &j)
int vnucextra () const
std::string xc () const
Public Member Functions inherited from madness::QCCalculationParametersBase
template<typename T >
T get (const std::string key) const
ParameterContainerT get_all_parameters () const
QCParameter & get_parameter (const std::string key)
hashT hash () const
bool is_user_defined (std::string key) const
bool parameter_exists (const std::string &key) const
void print (const std::string header="", const std::string footer="") const
print all parameters
std::string print_to_string (bool non_defaults_only=false) const
virtual void read_internal (World &world, std::string &filecontents, std::string tag)
read the stream, starting from tag
template<typename Archive >
void serialize (Archive &ar)
template<typename T >
void set_derived_value (const std::string &key, const T &value)
template<typename T >
void set_user_defined_value (const std::string &key, const T &value)
Additional Inherited Members
Static Public Member Functions inherited from madness::QCCalculationParametersBase
static std::string add_quotes (const std::string arg)
template<typename T >
static bool check_type (const std::string key, const QCParameter &parameter)
template<typename T >
static bool check_type_silent (const QCParameter &parameter)
template<typename T >
static std::enable_if<!std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_same< T, bool >::value, T >::type fromstring (const std::string &arg)
template<typename T >
static std::enable_if< std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if<!std::is_floating_point< T >::value, void >::type overwrite_if_inf (std::string &str, const T &arg)
template<typename T >
static std::enable_if< std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
template<typename T >
static std::enable_if<!std::is_same< T, std::string >::value, T >::type read_quotes (std::stringstream &ssvalue)
static std::string tostring (const bool &arg)
template<typename T >
static std::string tostring (const T &arg)
static std::string trim_blanks (const std::string arg)
static std::string trim_quotes (const std::string arg)
Protected Types inherited from madness::QCCalculationParametersBase
typedef std::map< std::string, QCParameter > ParameterContainerT
Protected Member Functions inherited from madness::QCCalculationParametersBase
QCCalculationParametersBase ()
ctor for testing
QCCalculationParametersBase (const QCCalculationParametersBase &other)
copy ctor
virtual ~QCCalculationParametersBase ()
destructor
const QCParameter & get_parameter (const std::string key) const
template<typename T >
void initialize (const std::string &key, const T &value, const std::string comment="", const std::vector< T > allowed_values={})
virtual void read_input_and_commandline_options (World &world, const commandlineparser &parser, const std::string tag)
template<typename T >
bool try_setting_user_defined_value (const std::string &key, const std::string &val)
Protected Attributes inherited from madness::QCCalculationParametersBase
bool ignore_unknown_keys =true
bool ignore_unknown_keys_silently =false
ParameterContainerT parameters
bool print_debug =false
bool throw_if_datagroup_not_found =true
Constructor & Destructor Documentation
ResponseParameters() [1/2]
madness::ResponseParameters::ResponseParameters (const ResponseParameters & other) default
ResponseParameters() [2/2]
madness::ResponseParameters::ResponseParameters () inline
References e().
Member Function Documentation
archive()
std::string madness::ResponseParameters::archive () const inline
Referenced by TDDFT::load(), and TDDFT::save().
calc_type()
std::string madness::ResponseParameters::calc_type () const inline
Referenced by TDDFT::iterate_excited(), TDDFT::update_x_space_excited(), and TDDFT::update_x_space_response().
core_type()
std::string madness::ResponseParameters::core_type () const inline
Referenced by TDDFT::make_nuclear_potential().
d2_types()
std::string madness::ResponseParameters::d2_types () const inline
Referenced by set_derived_values().
dconv()
double madness::ResponseParameters::dconv () const inline
Referenced by TDDFT::GetFullResponseTransformation(), TDDFT::iterate_excited(), TDDFT::iterate_freq2(), and TDDFT::set_protocol().
dconv_set()
bool madness::ResponseParameters::dconv_set () const inline
Referenced by TDDFT::set_protocol().
dipole()
bool madness::ResponseParameters::dipole () const inline
Referenced by main(), set_derived_values(), and TDDFT::solve_response_states().
e_range()
bool madness::ResponseParameters::e_range () const inline
e_range_hi()
double madness::ResponseParameters::e_range_hi () const inline
Referenced by TDDFT::select_active_subspace().
e_range_lo()
double madness::ResponseParameters::e_range_lo () const inline
Referenced by TDDFT::select_active_subspace().
econv()
double madness::ResponseParameters::econv () const inline
excited_state()
bool madness::ResponseParameters::excited_state () const inline
Referenced by density_vector::density_vector(), main(), and set_derived_values().
first_order()
bool madness::ResponseParameters::first_order () const inline
Referenced by main(), and set_derived_values().
first_run()
bool madness::ResponseParameters::first_run () const inline
guess_max_iter()
size_t madness::ResponseParameters::guess_max_iter () const inline
Referenced by TDDFT::iterate_guess().
guess_xyz()
bool madness::ResponseParameters::guess_xyz () const inline
Referenced by TDDFT::solve_excited_states().
k()
int madness::ResponseParameters::k () const inline
Referenced by TDDFT::set_protocol().
kain()
bool madness::ResponseParameters::kain () const inline
Referenced by TDDFT::iterate_excited(), TDDFT::iterate_freq2(), TDDFT::update_x_space_excited(), and TDDFT::update_x_space_response().
L()
double madness::ResponseParameters::L () const inline
Referenced by TDDFT::iterate_excited(), TDDFT::iterate_freq2(), TDDFT::plot_excited_states(), TDDFT::PlotGroundandResponseOrbitals(), TDDFT::solve_excited_states(), TDDFT::solve_response_states(), and TDDFT::TDDFT().
larger_subspace()
size_t madness::ResponseParameters::larger_subspace () const inline
Referenced by TDDFT::deflateFull(), and TDDFT::deflateTDA().
lo()
double madness::ResponseParameters::lo () const inline
Referenced by TDDFT::bsh_update_excited(), TDDFT::Coulomb(), TDDFT::CreateGroundHamiltonian(), TDDFT::iterate_guess(), TDDFT::make_bsh_operators_response(), TDDFT::PropertyRHS(), and TDDFT::set_protocol().
load_density()
bool madness::ResponseParameters::load_density () const inline
load_density_file()
std::string madness::ResponseParameters::load_density_file () const inline
loadbalparts()
int madness::ResponseParameters::loadbalparts () const inline
Referenced by TDDFT::initial_load_bal(), TDDFT::load_balance(), and TDDFT::orbital_load_balance().
local()
std::string madness::ResponseParameters::local () const inline
localize()
std::string madness::ResponseParameters::localize () const inline
Referenced by TDDFT::Compute_Theta_X().
maxiter()
size_t madness::ResponseParameters::maxiter () const inline
Referenced by TDDFT::iterate_excited(), TDDFT::iterate_freq2(), and TDDFT::update_x_space_excited().
maxrotn()
double madness::ResponseParameters::maxrotn () const inline
Referenced by TDDFT::do_step_restriction(), TDDFT::iterate_excited(), and TDDFT::iterate_freq2().
maxsub()
size_t madness::ResponseParameters::maxsub () const inline
Referenced by TDDFT::iterate_excited(), and TDDFT::iterate_freq2().
nuclear()
bool madness::ResponseParameters::nuclear () const inline
Referenced by set_derived_values(), and TDDFT::solve_response_states().
num_orbitals()
size_t madness::ResponseParameters::num_orbitals () const inline
Referenced by TDDFT::compute_gamma_static(), TDDFT::iterate_excited(), TDDFT::iterate_freq2(), TDDFT::iterate_guess(), TDDFT::load(), TDDFT::orbital_load_balance(), TDDFT::PropertyRHS(), TDDFT::save(), TDDFT::select_active_subspace(), TDDFT::solve_excited_states(), TDDFT::solve_response_states(), and TDDFT::TDDFT().
num_states()
size_t madness::ResponseParameters::num_states () const inline
Referenced by TDDFT::compute_gamma_static(), TDDFT::CreateBSHOperatorPropertyVector(), TDDFT::deflateFull(), TDDFT::deflateTDA(), density_vector::density_vector(), TDDFT::iterate_excited(), TDDFT::iterate_freq2(), TDDFT::iterate_guess(), TDDFT::load(), TDDFT::orbital_load_balance(), TDDFT::save(), TDDFT::solve_excited_states(), and TDDFT::solve_response_states().
nwchem()
bool madness::ResponseParameters::nwchem () const inline
Referenced by TDDFT::solve_excited_states().
nwchem_dir()
std::string madness::ResponseParameters::nwchem_dir () const inline
Referenced by TDDFT::create_nwchem_guess().
omega()
double madness::ResponseParameters::omega () const inline
Referenced by TDDFT::bsh_update_response(), density_vector::density_vector(), TDDFT::iterate_freq2(), TDDFT::load_balance(), set_derived_values(), and TDDFT::update_x_space_response().
order2()
bool madness::ResponseParameters::order2 () const inline
Referenced by TDDFT::solve_response_states().
order3()
bool madness::ResponseParameters::order3 () const inline
Referenced by TDDFT::solve_response_states().
plot()
bool madness::ResponseParameters::plot () const inline
Referenced by TDDFT::iterate_excited(), TDDFT::iterate_freq2(), TDDFT::solve_excited_states(), and TDDFT::solve_response_states().
plot_all_orbitals()
bool madness::ResponseParameters::plot_all_orbitals () const inline
Referenced by TDDFT::iterate_excited(), and TDDFT::iterate_freq2().
plot_cell()
std::vector<double> madness::ResponseParameters::plot_cell () const inline
plot_data()
std::vector<int> madness::ResponseParameters::plot_data () const inline
Referenced by TDDFT::solve_excited_states(), and TDDFT::solve_response_states().
plot_initial()
bool madness::ResponseParameters::plot_initial () const inline
Referenced by TDDFT::solve_excited_states(), and TDDFT::solve_response_states().
plot_l()
double madness::ResponseParameters::plot_l () const inline
Referenced by TDDFT::solve_excited_states(), and TDDFT::solve_response_states().
plot_pts()
size_t madness::ResponseParameters::plot_pts () const inline
Referenced by TDDFT::solve_excited_states(), and TDDFT::solve_response_states().
plot_range()
bool madness::ResponseParameters::plot_range () const inline
print_level()
int madness::ResponseParameters::print_level () const inline
Referenced by TDDFT::analyze_vectors(), TDDFT::apply_shift(), TDDFT::bsh_update_excited(), TDDFT::check_k(), TDDFT::compute_F0X(), TDDFT::compute_gamma_full(), TDDFT::compute_gamma_tda(), TDDFT::Compute_Lambda_X(), TDDFT::compute_new_omegas_transform(), TDDFT::compute_residual(), TDDFT::Compute_Theta_X(), TDDFT::compute_V0X(), TDDFT::create_bsh_operators(), TDDFT::CreateBSHOperatorPropertyVector(), TDDFT::deflateFull(), TDDFT::deflateGuesses(), TDDFT::deflateTDA(), density_vector::density_vector(), TDDFT::diagonalize_CIS_guess(), TDDFT::diagonalizeFockMatrix(), TDDFT::diagonalizeFullResponseMatrix(), TDDFT::do_step_restriction(), TDDFT::get_fock_transformation(), TDDFT::GetFullResponseTransformation(), TDDFT::iterate_excited(), TDDFT::iterate_freq2(), TDDFT::iterate_guess(), TDDFT::make_bsh_operators_response(), TDDFT::print_residual_norms(), TDDFT::PropertyRHS(), TDDFT::select_active_subspace(), TDDFT::TDDFT(), and TDDFT::update_x_space_response().
property()
bool madness::ResponseParameters::property () const inline
protocol()
std::vector<double> madness::ResponseParameters::protocol () const inline
Referenced by TDDFT::solve_excited_states(), and TDDFT::solve_response_states().
random()
bool madness::ResponseParameters::random () const inline
Referenced by TDDFT::solve_excited_states().
read_input_and_commandline_options()
virtual void madness::QCCalculationParametersBase::read_input_and_commandline_options inline
restart()
bool madness::ResponseParameters::restart () const inline
Referenced by TDDFT::solve_excited_states(), and TDDFT::solve_response_states().
restart_file()
std::string madness::ResponseParameters::restart_file () const inline
Referenced by TDDFT::solve_excited_states(), and TDDFT::solve_response_states().
save()
bool madness::ResponseParameters::save () const inline
Referenced by TDDFT::iterate_excited(), TDDFT::iterate_freq2(), and TDDFT::solve_excited_states().
save_density()
bool madness::ResponseParameters::save_density () const inline
save_density_file()
std::string madness::ResponseParameters::save_density_file () const inline
save_file()
std::string madness::ResponseParameters::save_file () const inline
Referenced by TDDFT::iterate_excited(), TDDFT::iterate_freq2(), and TDDFT::solve_excited_states().
second_order()
bool madness::ResponseParameters::second_order () const inline
Referenced by main(), and set_derived_values().
set_derived_values()
void madness::ResponseParameters::set_derived_values (World & world, Molecule molecule) inline
References d2_types(), dipole(), excited_state(), first_order(), MADNESS_EXCEPTION, molecule, madness::Molecule::natom(), nuclear(), omega(), second_order(), tda(), and third_order().
set_ground_state_calculation_data()
void madness::ResponseParameters::set_ground_state_calculation_data (GroundStateCalculation g_params) inline
References GroundStateCalculation::get_L(), GroundStateCalculation::get_xc(), GroundStateCalculation::is_spinrestricted(), GroundStateCalculation::molecule(), GroundStateCalculation::n_orbitals(), and madness::Molecule::smallest_length_scale().
spinrestricted()
bool madness::ResponseParameters::spinrestricted () const inline
Referenced by density_vector::density_vector().
store_potential()
bool madness::ResponseParameters::store_potential () const inline
Referenced by TDDFT::check_k(), TDDFT::compute_V0X(), and TDDFT::CreateGroundHamiltonian().
tda()
bool madness::ResponseParameters::tda () const inline
Referenced by TDDFT::analysis(), TDDFT::bsh_update_excited(), TDDFT::compute_new_omegas_transform(), TDDFT::iterate_excited(), TDDFT::iterate_guess(), TDDFT::load(), TDDFT::save(), set_derived_values(), and TDDFT::update_x_space_excited().
third_order()
bool madness::ResponseParameters::third_order () const inline
Referenced by set_derived_values().
to_json()
void ResponseParameters::to_json (nlohmann::json & j)
References p(), and madness::QCCalculationParametersBase::parameters.
Referenced by main(), and TDDFT::TDDFT().
vnucextra()
int madness::ResponseParameters::vnucextra () const inline
Referenced by TDDFT::initial_load_bal(), and TDDFT::load_balance().
xc()
std::string madness::ResponseParameters::xc () const inline
Referenced by TDDFT::create_fxc(), TDDFT::CreateGroundHamiltonian(), TDDFT::CreateXCDerivative(), density_vector::density_vector(), TDDFT::GetConjugateWxcOnFDensities(), TDDFT::GetWxcOnFDensities(), TDDFT::iterate_excited(), TDDFT::iterate_freq2(), and TDDFT::iterate_guess().
The documentation for this struct was generated from the following files:
response_parameters.h
response_parameters.cpp