MADNESS: madness::FunctionImpl< T, NDIM >::do_standard Struct Reference
madness::FunctionImpl< T, NDIM >::do_standard Struct Reference
Changes non-standard compressed form to standard compressed form.
#include <funcimpl.h>
Public Types
typedef Range< typename dcT::iterator > rangeT
Public Member Functions
do_standard ()
do_standard (implT *impl)
bool operator() (typename rangeT::iterator &it) const
template<typename Archive >
void serialize (const Archive &ar)
Public Attributes
implT * impl
Detailed Description
template<typename T, std::size_t NDIM>
struct madness::FunctionImpl< T, NDIM >::do_standard
Changes non-standard compressed form to standard compressed form.
Member Typedef Documentation
rangeT
template<typename T , std::size_t NDIM> typedef Range<typename dcT::iterator> madness::FunctionImpl< T, NDIM >::do_standard::rangeT
Constructor & Destructor Documentation
do_standard() [1/2]
template<typename T , std::size_t NDIM> madness::FunctionImpl< T, NDIM >::do_standard::do_standard () inline
do_standard() [2/2]
template<typename T , std::size_t NDIM> madness::FunctionImpl< T, NDIM >::do_standard::do_standard (implT * impl) inline
Member Function Documentation
operator()()
template<typename T , std::size_t NDIM> bool madness::FunctionImpl< T, NDIM >::do_standard::operator() (typename rangeT::iterator & it) const inline
References madness::FunctionImpl< T, NDIM >::cdata, madness::FunctionNode< T, NDIM >::clear_coeff(), madness::FunctionNode< T, NDIM >::coeff(), madness::GenTensor< T >::dim(), madness::FunctionImpl< T, NDIM >::get_k(), madness::FunctionNode< T, NDIM >::has_children(), madness::FunctionNode< T, NDIM >::has_coeff(), madness::FunctionImpl< T, NDIM >::do_standard::impl, madness::Key< NDIM >::level(), madness::FunctionImpl< T, NDIM >::MADNESS_ASSERT(), madness::FunctionNode< T, NDIM >::reduceRank(), madness::FunctionImpl< T, NDIM >::targs, and madness::TensorArgs::thresh.
serialize()
template<typename T , std::size_t NDIM> template<typename Archive > void madness::FunctionImpl< T, NDIM >::do_standard::serialize (const Archive & ar) inline
References MADNESS_EXCEPTION.
Member Data Documentation
impl
template<typename T , std::size_t NDIM> implT* madness::FunctionImpl< T, NDIM >::do_standard::impl
Referenced by madness::FunctionImpl< T, NDIM >::do_standard::operator()().
The documentation for this struct was generated from the following file:
funcimpl.h