MADNESS: madness::X_space Struct Reference
madness::X_space Struct Reference
#include <x_space.h>
Public Member Functions
X_space ()
X_space (const X_space &A)
X_space (response_space &X, response_space &Y)
X_space (World &world, size_t n_states, size_t n_orbtials)
void clear ()
X_space copy () const
X_space copy (const std::shared_ptr< WorldDCPmapInterface< Key< 3 > > > &pmap, bool fence=false) const
size_t num_orbitals () const
size_t num_states () const
X_space operator* (const double &b)
X_space operator+ (const X_space B)
X_space & operator+= (const X_space B)
X_space operator- (const X_space B)
X_space & operator= (const X_space &B)
void pop_back ()
void print_norm2 ()
void push_back (vector_real_function_3d x, vector_real_function_3d y)
void truncate ()
Public Attributes
response_space X
response_space Y
Private Attributes
size_t n_orbitals
size_t n_states
Friends
Tensor< double > inner (X_space &A, X_space &B)
X_space operator* (const double &b, const X_space &A)
X_space operator* (const Function< double, 3 > &f, const X_space &A)
X_space operator* (const X_space &A, const double &b)
X_space operator* (const X_space &A, const Function< double, 3 > &f)
X_space operator* (const X_space &A, const Tensor< double > &b)
X_space operator+ (const X_space &A, const X_space &B)
X_space operator- (const X_space &A, const X_space &B)
bool same_size (const X_space &A, const X_space &B)
size_t size_orbitals (const X_space &x)
size_t size_states (const X_space &x)
Constructor & Destructor Documentation
X_space() [1/4]
madness::X_space::X_space () inline
X_space() [2/4]
madness::X_space::X_space (const X_space & A) inline
X_space() [3/4]
madness::X_space::X_space (World & world, size_t n_states, size_t n_orbtials) inline
X_space() [4/4]
madness::X_space::X_space (response_space & X, response_space & Y) inline explicit
References madness::response_space::copy(), MADNESS_ASSERT, madness::response_space::size(), X, and Y.
Member Function Documentation
clear()
void madness::X_space::clear () inline
References madness::response_space::clear(), X, and Y.
Referenced by TDDFT::compute_gamma_full(), TDDFT::compute_gamma_static(), TDDFT::compute_gamma_tda(), and TDDFT::solve_excited_states().
copy() [1/2]
X_space madness::X_space::copy () const inline
References madness::response_space::copy(), n_orbitals, n_states, X, and Y.
Referenced by TDDFT::compute_F0X(), TDDFT::Compute_Lambda_X(), TDDFT::Compute_Theta_X(), TDDFT::deflateFull(), TDDFT::iterate_freq2(), TDDFT::orbital_load_balance(), TDDFT::unaugment_full(), TDDFT::update_x_space_excited(), and TDDFT::update_x_space_response().
copy() [2/2]
X_space madness::X_space::copy (const std::shared_ptr< WorldDCPmapInterface< Key< 3 > > > & pmap, bool fence = false) const inline
Create a new copy of the function with different distribution and optional fence Works in either basis. Different distributions imply asynchronous communication and the optional fence is collective.
References madness::response_space::copy(), n_orbitals, n_states, X, and Y.
num_orbitals()
size_t madness::X_space::num_orbitals () const inline
References n_orbitals.
Referenced by TDDFT::bsh_update_excited(), TDDFT::compute_F0X(), TDDFT::compute_gamma_full(), TDDFT::compute_gamma_tda(), TDDFT::Compute_Theta_X(), TDDFT::compute_V0X(), madness::do_vtk_plots(), TDDFT::kain_x_space_update(), print_norm2(), and push_back().
num_states()
size_t madness::X_space::num_states () const inline
References n_states.
Referenced by TDDFT::augment_full(), TDDFT::bsh_update_excited(), TDDFT::compute_F0X(), TDDFT::compute_gamma_full(), TDDFT::compute_gamma_tda(), TDDFT::Compute_Theta_X(), TDDFT::compute_V0X(), TDDFT::create_nwchem_guess(), madness::do_vtk_plots(), TDDFT::iterate_excited(), TDDFT::iterate_freq2(), TDDFT::kain_x_space_update(), TDDFT::normalize(), print_norm2(), TDDFT::print_residual_norms(), TDDFT::update_x_space_excited(), TDDFT::update_x_space_response(), and TDDFT::x_space_step_restriction().
operator*()
X_space madness::X_space::operator* (const double & b) inline
References b.
operator+()
X_space madness::X_space::operator+ (const X_space B) inline
References MADNESS_ASSERT, n_orbitals, n_states, same_size, X, and Y.
operator+=()
X_space& madness::X_space::operator+= (const X_space B) inline
References MADNESS_ASSERT, and same_size.
operator-()
X_space madness::X_space::operator- (const X_space B) inline
References MADNESS_ASSERT, n_orbitals, n_states, same_size, X, and Y.
operator=()
X_space& madness::X_space::operator= (const X_space & B) inline
References size_orbitals, and size_states.
pop_back()
void madness::X_space::pop_back () inline
References n_orbitals, n_states, madness::response_space::pop_back(), X, and Y.
Referenced by TDDFT::unaugment_full().
print_norm2()
void madness::X_space::print_norm2 () inline
References madness::response_space::norm2(), num_orbitals(), num_states(), X, and Y.
push_back()
void madness::X_space::push_back (vector_real_function_3d x, vector_real_function_3d y) inline
References MADNESS_ASSERT, n_orbitals, n_states, num_orbitals(), madness::response_space::push_back(), X, and Y.
Referenced by TDDFT::augment_full().
truncate()
void madness::X_space::truncate () inline
References madness::response_space::truncate_rf(), X, and Y.
Referenced by TDDFT::bsh_update_excited(), TDDFT::bsh_update_response(), TDDFT::compute_gamma_full(), TDDFT::compute_gamma_static(), TDDFT::Compute_Lambda_X(), TDDFT::Compute_Theta_X(), TDDFT::compute_V0X(), and TDDFT::deflateFull().
Friends And Related Function Documentation
inner
Tensor<double> inner (X_space & A, X_space & B) friend
operator* [1/5]
X_space operator* (const double & b, const X_space & A) friend
operator* [2/5]
X_space operator* (const Function< double, 3 > & f, const X_space & A) friend
operator* [3/5]
X_space operator* (const X_space & A, const double & b) friend
operator* [4/5]
X_space operator* (const X_space & A, const Function< double, 3 > & f) friend
operator* [5/5]
X_space operator* (const X_space & A, const Tensor< double > & b) friend
operator+
X_space operator+ (const X_space & A, const X_space & B) friend
operator-
X_space operator- (const X_space & A, const X_space & B) friend
same_size
bool same_size (const X_space & A, const X_space & B) friend
Referenced by operator+(), operator+=(), madness::X_vector::operator+=(), and operator-().
size_orbitals
size_t size_orbitals (const X_space & x) friend
Referenced by operator=().
size_states
size_t size_states (const X_space & x) friend
Referenced by operator=().
Member Data Documentation
n_orbitals
size_t madness::X_space::n_orbitals private
Referenced by copy(), num_orbitals(), operator+(), operator-(), pop_back(), and push_back().
n_states
size_t madness::X_space::n_states private
Referenced by copy(), num_states(), operator+(), operator-(), pop_back(), and push_back().
X
response_space madness::X_space::X
Referenced by TDDFT::analysis(), TDDFT::augment(), TDDFT::augment_full(), TDDFT::bsh_update_excited(), TDDFT::bsh_update_response(), TDDFT::check_k(), clear(), TDDFT::compute_F0X(), TDDFT::compute_gamma_full(), TDDFT::compute_gamma_static(), TDDFT::compute_gamma_tda(), TDDFT::Compute_Lambda_X(), TDDFT::compute_new_omegas_transform(), TDDFT::compute_residual(), TDDFT::Compute_Theta_X(), TDDFT::compute_V0X(), copy(), madness::X_vector::copy(), TDDFT::create_nwchem_guess(), TDDFT::create_trial_functions(), TDDFT::create_trial_functions2(), TDDFT::deflateFull(), TDDFT::deflateGuesses(), TDDFT::deflateTDA(), TDDFT::diagonalizeFockMatrix(), TDDFT::diagonalizeFullResponseMatrix(), madness::do_vtk_plots(), TDDFT::iterate_excited(), TDDFT::iterate_freq2(), TDDFT::iterate_guess(), TDDFT::kain_x_space_update(), TDDFT::load(), TDDFT::load_balance(), TDDFT::make_density(), TDDFT::normalize(), operator+(), madness::X_vector::operator+=(), operator-(), TDDFT::orbital_load_balance(), pop_back(), print_norm2(), TDDFT::print_residual_norms(), push_back(), TDDFT::save(), TDDFT::solve_excited_states(), TDDFT::solve_response_states(), TDDFT::sort(), truncate(), TDDFT::unaugment(), TDDFT::unaugment_full(), TDDFT::update_x_space_excited(), TDDFT::update_x_space_response(), X_space(), TDDFT::x_space_step_restriction(), and madness::X_vector::X_vector().
Y
response_space madness::X_space::Y
Referenced by TDDFT::analysis(), TDDFT::augment_full(), TDDFT::bsh_update_excited(), TDDFT::bsh_update_response(), TDDFT::check_k(), clear(), TDDFT::compute_F0X(), TDDFT::compute_gamma_full(), TDDFT::compute_gamma_static(), TDDFT::Compute_Lambda_X(), TDDFT::compute_residual(), TDDFT::Compute_Theta_X(), TDDFT::compute_V0X(), copy(), madness::X_vector::copy(), TDDFT::deflateFull(), TDDFT::diagonalizeFullResponseMatrix(), madness::do_vtk_plots(), TDDFT::iterate_excited(), TDDFT::iterate_freq2(), TDDFT::kain_x_space_update(), TDDFT::load(), TDDFT::load_balance(), TDDFT::make_density(), TDDFT::normalize(), operator+(), madness::X_vector::operator+=(), operator-(), TDDFT::orbital_load_balance(), pop_back(), print_norm2(), TDDFT::print_residual_norms(), push_back(), TDDFT::save(), TDDFT::solve_excited_states(), TDDFT::solve_response_states(), TDDFT::sort(), truncate(), TDDFT::unaugment_full(), TDDFT::update_x_space_excited(), TDDFT::update_x_space_response(), X_space(), TDDFT::x_space_step_restriction(), and madness::X_vector::X_vector().
The documentation for this struct was generated from the following file:
x_space.h