MADNESS: test_ccpairfunction.cc File Reference
test_ccpairfunction.cc File Reference
#include <madness/mra/mra.h>
#include <madness/chem/ccpairfunction.h>
#include <madness/chem/correlationfactor.h>
#include <madness/chem/electronic_correlation_factor.h>
#include <madness/chem/CCStructures.h>
#include <madness/chem/projector.h>
#include <madness/world/test_utilities.h>
Classes
struct data
Functions
int main (int argc, char **argv)
int test_apply (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, const Molecule &molecule, const CCParameters &parameter)
int test_constructor (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, const Molecule &molecule, const CCParameters &parameter)
int test_dirac_convolution (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, const Molecule &molecule, const CCParameters &parameter)
int test_overlap (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, const Molecule &molecule, const CCParameters &parameters)
int test_partial_inner (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, const Molecule &molecule, const CCParameters &parameter)
int test_projector (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, const Molecule &molecule, const CCParameters &parameter)
int test_scalar_multiplication (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, const Molecule &molecule, const CCParameters &parameter)
int test_swap_particles (World &world, std::shared_ptr< NuclearCorrelationFactor > ncf, const Molecule &molecule, const CCParameters &parameters)
Variables
data data1
Function Documentation
main()
int main (int argc, char ** argv)
functionality
ctor OK
assignment OK
add
scalar multiplication OK
inner OK
inner_partial OK
swap_particles OK
apply
apply_partial (i.e. exchange)
serialize
collapse_to_pure (excl g!)
mul_partial
References data::clear(), madness::create_nuclear_correlation_factor(), data1, e(), madness::finalize(), madness::initialize(), madness::print(), madness::Molecule::print(), madness::commandlineparser::print_map(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::commandlineparser::set_keyval(), madness::FunctionDefaults< NDIM >::set_tensor_type(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), test_constructor(), test_overlap(), test_partial_inner(), test_projector(), test_scalar_multiplication(), test_swap_particles(), and madness::TT_2D.
test_apply()
int test_apply (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, const Molecule & molecule, const CCParameters & parameter)
References madness::test_output::get_final_success().
test_constructor()
int test_constructor (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, const Molecule & molecule, const CCParameters & parameter)
References a, a1, b, madness::test_output::checkpoint(), madness::CCPairFunction::component, data1, madness::test_output::end(), madness::f, f1, f2, f3, madness::test_output::get_final_success(), data::get_functions(), madness::CCPairFunction::is_decomposed(), madness::CCPairFunction::is_op_decomposed(), madness::CCPairFunction::is_pure(), MADNESS_CHECK, op(), madness::OT_F12, p(), and madness::CCPairFunction::pure().
Referenced by main().
test_dirac_convolution()
int test_dirac_convolution (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, const Molecule & molecule, const CCParameters & parameter)
References madness::test_output::get_final_success().
test_overlap()
int test_overlap (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, const Molecule & molecule, const CCParameters & parameters)
References a, aa, b, madness::test_output::checkpoint(), madness::copy(), diff(), e(), madness::f, f1, f2, madness::Function< T, NDIM >::fill_tree(), madness::g, madness::CompositeFactory< T, NDIM, MDIM >::g12(), madness::CCParameters::gamma(), madness::test_output::get_final_success(), madness::CC_vecfunction::get_vecfunction(), madness::HOLE, madness::inner(), lo, madness::CCParameters::lo(), max, molecule, madness::detail::norm(), madness::OT_F12, madness::OT_G12, madness::CompositeFactory< T, NDIM, MDIM >::particle1(), madness::CompositeFactory< T, NDIM, MDIM >::particle2(), madness::print(), madness::Function< T, NDIM >::print_size(), R2, madness::World::rank(), madness::Function< T, NDIM >::reduce_rank(), madness::Function< T, NDIM >::scale(), madness::test_output::set_cout_to_terminal(), madness::CC_vecfunction::size(), madness::SlaterF12Operator(), madness::SlaterOperator(), test1(), test2(), madness::CCParameters::thresh_3D(), madness::CCParameters::thresh_6D(), madness::CCParameters::thresh_bsh_3D(), timer(), madness::truncate(), and madness::Function< T, NDIM >::truncate().
Referenced by main().
test_partial_inner()
int test_partial_inner (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, const Molecule & molecule, const CCParameters & parameter)
References a, b, madness::test_output::checkpoint(), data1, madness::f, f1, f2, f3, madness::test_output::get_final_success(), data::get_functions(), madness::inner(), madness::detail::norm(), madness::OT_F12, madness::print(), and timer().
Referenced by main().
test_projector()
int test_projector (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, const Molecule & molecule, const CCParameters & parameter)
References a, aa, b, madness::test_output::checkpoint(), data1, madness::test_output::end(), madness::f, f1, f2, f3, madness::test_output::get_final_success(), data::get_functions(), madness::inner(), madness::matrix_inner(), madness::OT_F12, p(), madness::print(), madness::test_output::set_cout_to_logger(), madness::ProjectorBase::set_particle(), madness::QProjector< T, NDIM >::set_particle(), madness::StrongOrthogonalityProjector< T, NDIM >::set_spaces(), and timer().
Referenced by main().
test_scalar_multiplication()
int test_scalar_multiplication (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, const Molecule & molecule, const CCParameters & parameter)
References a, b, madness::test_output::checkpoint(), data1, madness::test_output::end(), madness::f, f1, f2, f3, madness::CCPairFunction::get_a(), madness::CCPairFunction::get_b(), madness::test_output::get_final_success(), data::get_functions(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::inner(), madness::norm2(), p(), madness::print(), and timer().
Referenced by main().
test_swap_particles()
int test_swap_particles (World & world, std::shared_ptr< NuclearCorrelationFactor > ncf, const Molecule & molecule, const CCParameters & parameters)
References a, std::abs(), b, madness::test_output::checkpoint(), data1, madness::test_output::end(), madness::f, f1, f2, f3, madness::test_output::get_final_success(), madness::CCPairFunction::get_function(), data::get_functions(), madness::inner(), madness::matrix_inner(), madness::norm2(), p(), madness::print(), R2, madness::CCPairFunction::swap_particles(), and timer().
Referenced by main().
Variable Documentation
data1
data data1
Referenced by main(), test_constructor(), test_partial_inner(), test_projector(), test_scalar_multiplication(), and test_swap_particles().