MADNESS: test_comm.cc File Reference
test_comm.cc File Reference
#include <madness/world/MADworld.h>
Classes
class Array
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References a, b, SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), SafeMPI::Finalize(), madness::Future< T >::get(), madness::World::gop, SafeMPI::Init(), MADNESS_CHECK, print(), madness::World::rand(), madness::World::rank(), and madness::World::size().