MADNESS: test_future.cc File Reference
test_future.cc File Reference
#include <madness/world/MADworld.h>
#include <string>
Classes
class Fred
Wrapper around vector demonstrating interface necessary.
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References Fred::a(), madness::WorldTaskQueue::add(), Fred::b(), SafeMPI::COMM_WORLD, madness::finalize(), fred(), madness::Future< T >::get(), madness::initialize(), madness::print(), madness::Future< T >::set(), madness::TaskAttributes::set_stealable(), and madness::World::taskq.