MADNESS: testttg.cc File Reference
testttg.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/mra/vmra.h>
#include <madness/mra/lbdeux.h>
#include <madness/constants.h>
#include <stdlib.h>
Classes
class Gaussian< T, NDIM >
class LevelPmapX
class PartitionPmap
A pmap that spatially decomposes the domain and by default slightly overdcomposes to attempt to load balance.
Functions
int main (int argc, char **argv)
void test2 (World &world, size_t nfunc, size_t k, double thresh)
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, e(), madness::finalize(), madness::initialize(), madness::startup(), and test2().
test2()
void test2 (World & world, size_t nfunc, size_t k, double thresh)
References a, madness::compress(), d(), drand48(), madness::WorldGopInterface::fence(), madness::func(), Gaussian, madness::World::gop, K(), k, L, N, madness::norm2s(), p(), pow(), madness::print(), madness::World::rank(), madness::reconstruct(), madness::FunctionDefaults< NDIM >::set_apply_randomize(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_pmap(), madness::FunctionDefaults< NDIM >::set_project_randomize(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), madness::World::size(), madness::ThreadPool::size(), thresh, and madness::wall_time().
Referenced by main().