MADNESS: test_cloud.cc File Reference
test_cloud.cc File Reference
#include <madness/mra/mra.h>
#include <madness/world/cloud.h>
#include <madness/mra/macrotaskq.h>
#include <madness/world/test_utilities.h>
Classes
struct gaussian
Functions
int chunk_example (World &universe)
test the cloud with message larger than chunk size set in cloud.replicate()
int main (int argc, char **argv)
template<typename T , std::size_t NDIM>
double norm (const Function< T, NDIM > &f1)
template<typename T , std::size_t NDIM>
double norm (const std::vector< Function< T, NDIM >> &f1)
template<typename T >
double norm (const std::vector< T > &v)
template<typename T >
double norm (const T i1)
template<typename T >
double norm (const Tensor< T > &t)
void simple_example (World &universe)
a simple example for how to use the cloud for inter-world communication
Function Documentation
chunk_example()
int chunk_example (World & universe)
test the cloud with message larger than chunk size set in cloud.replicate()
References std::abs(), madness::test_output::end(), madness::Cloud::load(), madness::Cloud::replicate(), madness::Cloud::store(), and madness::sum().
Referenced by main().
main()
int main (int argc, char ** argv)
References madness::arg(), chunk_example(), madness::Cloud::clear_cache(), madness::Cloud::clear_timings(), madness::MacroTaskQ::create_worlds(), e(), madness::test_output::end(), madness::error(), f1, f2, f3, madness::WorldGopInterface::fence(), madness::Tensor< T >::fillrandom(), madness::finalize(), gaussian(), madness::Function< T, NDIM >::get_impl(), madness::World::gop, madness::World::id(), madness::initialize(), madness::Cloud::load(), madness::test_output::logger, max, norm(), madness::Function< T, NDIM >::norm2(), madness::norm2(), madness::print(), madness::Cloud::print_timings(), madness::World::rank(), madness::Cloud::set_debug(), madness::Cloud::set_force_load_from_cache(), madness::Function< T, NDIM >::set_impl(), madness::MacroTaskQ::set_pmap(), simple_example(), madness::World::size(), madness::startup(), and madness::Cloud::store().
norm() [1/5]
template<typename T , std::size_t NDIM> double norm (const Function< T, NDIM > & f1)
References f1.
norm() [2/5]
template<typename T , std::size_t NDIM> double norm (const std::vector< Function< T, NDIM >> & f1)
References f1, and madness::norm2().
norm() [3/5]
template<typename T > double norm (const std::vector< T > & v)
References e().
norm() [4/5]
template<typename T > double norm (const T i1)
Referenced by main(), and simple_example().
norm() [5/5]
template<typename T > double norm (const Tensor< T > & t)
References madness::Tensor< T >::normf().
simple_example()
void simple_example (World & universe)
a simple example for how to use the cloud for inter-world communication
Notes:
during the subworld section no universe-wide fence must be invoked, including the creation of universe WorldObjects – they must be constructed before
Certain operation can be performed between objects living in different world (e.g. Function::operator+=) – store/lood pointers to these universe-wide world objects
when the subworld is destroyed all subworld objects must have been destroyed
subworld objects will be destroyed only at subworld fences
References madness::Cloud::clear_cache(), madness::MacroTaskQ::create_worlds(), madness::WorldGopInterface::fence(), gaussian(), madness::World::gop, madness::World::id(), madness::Cloud::load(), norm(), madness::Function< T, NDIM >::norm2(), madness::print(), madness::World::rank(), madness::MacroTaskQ::set_pmap(), madness::World::size(), and madness::Cloud::store().
Referenced by main().