MADNESS: test_tree.cc File Reference
test_tree.cc File Reference
#include <madness/world/MADworld.h>
#include <madness/world/worldhash.h>
Classes
struct Key
class KeyChildIterator
struct Node
Macros
#define WORLD_INSTANTIATE_STATIC_TEMPLATES
Functions
void doit (World &world)
int main (int argc, char **argv)
ostream & operator<< (ostream &s, const Key &key)
ostream & operator<< (ostream &s, const Node &node)
Macro Definition Documentation
WORLD_INSTANTIATE_STATIC_TEMPLATES
#define WORLD_INSTANTIATE_STATIC_TEMPLATES
Function Documentation
doit()
void doit (World & world)
References d(), Node::do_sum_spawn(), madness::WorldGopInterface::fence(), madness::World::gop, me, madness::print(), Node::random_insert(), madness::World::rank(), Node::recursive_print(), madness::WorldGopInterface::sum(), and madness::sum().
Referenced by main().
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, doit(), e(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::print(), and madness::redirectio().
operator<<() [1/2]
ostream& operator<< (ostream & s, const Key & key)
References madness::Key< NDIM >::n.
operator<<() [2/2]
ostream& operator<< (ostream & s, const Node & node)
References Node::get(), and Node::is_leaf().