MADNESS: test_macrotaskpartitioner.cc File Reference
test_macrotaskpartitioner.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/macrotaskpartitioner.h>
#include <madness/world/test_utilities.h>
Functions
int main (int argc, char **argv)
int test_batch (World &world)
int test_batch_1D (World &world)
int test_partitioner (World &world)
Function Documentation
main()
int main (int argc, char ** argv)
References madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::startup(), test_batch(), test_batch_1D(), and test_partitioner().
test_batch()
int test_batch (World & world)
References madness::Batch::copy_input_batch(), madness::get_impl(), madness::Batch::insert_result_batch(), MADNESS_CHECK, and madness::print().
Referenced by main().
test_batch_1D()
int test_batch_1D (World & world)
References b, madness::Batch_1D::copy_batch(), madness::get_impl(), madness::Batch_1D::insert_batch(), madness::Batch_1D::is_full_size(), MADNESS_CHECK, madness::print(), and madness::Batch_1D::size().
Referenced by main().
test_partitioner()
int test_partitioner (World & world)
References p(), madness::MacroTaskPartitioner::partition_tasks(), madness::print(), madness::MacroTaskPartitioner::set_dimension(), and madness::MacroTaskPartitioner::set_nsubworld().
Referenced by main().