MADNESS: test_response_functions.cpp File Reference
test_response_functions.cpp File Reference
#include "madness/tensor/tensor_json.hpp"
#include "response_functions.h"
#include "timer.h"
#include "string"
#include "x_space.h"
Functions
TEST_CASE ("Test Response Functions", "Testing Basic Functionality of Response Functions")
Function Documentation
TEST_CASE()
TEST_CASE ("Test Response Functions" , "Testing Basic Functionality of Response Functions")
References SafeMPI::COMM_WORLD, molresponse::end_timer(), madness::finalize(), initialize(), molresponse::start_timer(), and madness::startup().