MADNESS: testgconv.cc File Reference
testgconv.cc File Reference
Test convolution with Gaussian * polyn.
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/constants.h>
Functions
double conv_prime_g (const coord_1d &r)
double convg (const coord_1d &r)
double g (const coord_1d &r)
double gconvh (const coord_1d &r)
double gprime (const coord_1d &r)
double h (const coord_1d &r)
int main (int argc, char **argv)
int test_gconv (World &world)
Variables
static const int k = 10
static const double L = 17
static const double thresh = 1e-6
Detailed Description
Test convolution with Gaussian * polyn.
Function Documentation
conv_prime_g()
double conv_prime_g (const coord_1d & r)
References madness::constants::pi.
Referenced by test_gconv().
convg()
double convg (const coord_1d & r)
References madness::constants::pi.
Referenced by test_gconv().
g()
double g (const coord_1d & r)
References madness::constants::pi.
Referenced by TDDFT::create_fxc(), fit(), TDDFT::gram_schmidt(), makedata(), TDDFT::normalize(), operator<<(), TDDFT::PrintRFExpectation(), AtomicBasisSet::read_file(), and updatex().
gconvh()
double gconvh (const coord_1d & r)
Referenced by test_gconv().
gprime()
double gprime (const coord_1d & r)
References madness::constants::pi.
Referenced by test_gconv().
h()
double h (const coord_1d & r)
Referenced by arithmetic_series(), madness::GFit< T, NDIM >::bsh_fit(), madness::GFit< T, NDIM >::bsh_fit_ndim(), madness::ConcurrentHashMap< void *, uniqueidT, hashvoidp >::ConcurrentHashMap(), madness::FunctionImpl< Q, NDIM >::do_print_grid(), madness::FunctionImpl< Q, NDIM >::downsample(), madness::fcube(), fit(), gen_ce(), QuasiNewton::hessian_update_bfgs(), QuasiNewton::hessian_update_sr1(), main(), madness::Nemo::make_incomplete_hessian_response_part(), make_pts(), QuasiNewton::new_search_direction(), BoysLocalization::operator()(), madness::ConcurrentHashMap< void *, uniqueidT, hashvoidp >::operator=(), QuasiNewton::optimize(), madness::FunctionImpl< Q, NDIM >::partial_inner(), madness::FunctionImpl< Q, NDIM >::partial_inner_contract(), madness::SeparatedConvolution< T, NDIM >::partial_upsample(), plot(), madness::FunctionImpl< Q, NDIM >::plot_cube_kernel(), madness::plot_line(), Calculation::plot_p(), madness::plotdx(), madness::RMI::RmiTask::process_some(), madness::FunctionImpl< Q, NDIM >::read_grid(), madness::FunctionImpl< Q, NDIM >::read_grid2(), madness::GaussianConvolution1D< Q >::rnlp(), madness::GFit< T, NDIM >::slater_fit(), madness::Nemo::solve_cphf(), test(), test_gconv(), test_plot(), updatex(), madness::SeparatedConvolution< T, NDIM >::upsample(), and madness::FunctionImpl< Q, NDIM >::upsample().
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, e(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), k, L, madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::startup(), test_gconv(), and thresh.
test_gconv()
int test_gconv (World & world)
References conv_prime_g(), convg(), madness::error(), exact(), madness::f, madness::WorldGopInterface::fence(), madness::g, gconvh(), madness::World::gop, gprime(), h(), k, L, lo, madness::norm2(), op(), madness::constants::pi, madness::plot_line(), madness::print(), q(), madness::World::rank(), and madness::Function< T, NDIM >::trace().
Referenced by main().
Variable Documentation
k
const int k = 10 static
Referenced by main(), and test_gconv().
L
const double L = 17 static
Referenced by main(), and test_gconv().
thresh
const double thresh = 1e-6 static
Referenced by main().