MADNESS: test_hashdc.cc File Reference
test_hashdc.cc File Reference
#include <madness/world/MADworld.h>
#include <madness/world/worlddc.h>
Classes
struct madness::archive::ArchiveSerializeImpl< Archive, Key >
struct Key
Namespaces
madness
File holds all helper structures necessary for the CC_Operator and CC2 class.
madness::archive
Namespace for I/O tools.
Macros
#define WORLD_INSTANTIATE_STATIC_TEMPLATES
Functions
hashT hash_value (const Key &key)
int main (int argc, char **argv)
ostream & operator<< (ostream &s, const Key &key)
Macro Definition Documentation
WORLD_INSTANTIATE_STATIC_TEMPLATES
#define WORLD_INSTANTIATE_STATIC_TEMPLATES
Function Documentation
hash_value()
hashT hash_value (const Key & key)
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), madness::finalize(), fred(), madness::World::gop, and madness::initialize().
operator<<()
ostream& operator<< (ostream & s, const Key & key)