MADNESS: test_derivative.cc File Reference
test_derivative.cc File Reference
#include "madness.h"
Classes
struct F
class G
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References madness::apply(), SafeMPI::COMM_WORLD, madness::Function< T, NDIM >::compress(), madness::copy(), e(), madness::f, madness::WorldGopInterface::fence(), madness::finalize(), G, madness::World::gop, madness::initialize(), madness::inner(), k, lo, madness::plot_line(), madness::print(), madness::Function< T, NDIM >::print_tree(), madness::project(), madness::Function< T, NDIM >::reconstruct(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), madness::startup(), and thresh.