MADNESS: test_density_vector.cpp File Reference
test_density_vector.cpp File Reference
#include "molresponse/ResponseExceptions.hpp"
#include "molresponse/densityVector.hpp"
#include "molresponse/global_functions.h"
#include <madness/world/worldmem.h>
Functions
TEST_CASE ("Test Density Vectors", "Testing Basic Functionality of Response Functions")
Function Documentation
TEST_CASE()
TEST_CASE ("Test Density Vectors" , "Testing Basic Functionality of Response Functions")
References initialize_calc_params(), molecule, print(), madness::print_meminfo(), and madness::World::rank().