MADNESS: vtk.cc File Reference
vtk.cc File Reference
#include <madness/mra/mra.h>
Functions
void doplotptk (World &world, int step, const functionT &psi, double Lplot, long numpt, const char *fname)
template<typename T , int NDIM>
void plotvtk (const Function< T, NDIM > &function, const char *filename, const Tensor< double > &cell, const std::vector< long > &npt, bool binary)
Function Documentation
doplotptk()
void doplotptk (World & world, int step, const functionT & psi, double Lplot, long numpt, const char * fname)
References madness::_(), plotvtk(), print(), psi(), and madness::wall_time().
plotvtk()
template<typename T , int NDIM> void plotvtk (const Function< T, NDIM > & function, const char * filename, const Tensor< double > & cell, const std::vector< long > & npt, bool binary)
References f, madness::filename, k, MADNESS_ASSERT, MADNESS_EXCEPTION, NDIM, and PROFILE_FUNC.
Referenced by doplotptk().